#!/usr/bin/env zsh

fpath=($fpath /etc/zsh/func)
typeset -U fpath


# Sofin SHELL_PID value:
export SHELL_PID="$$"

# Sofin launcher function:
s () {
    eval /Software/Sofin/bin/s ${@}
}

# Trap USR2 signal to reload ~/.profile:
trap '. "${HOME}/.profile"' USR2
if [ -e "${HOME}/.profile" ]; then
    source "${HOME}/.profile"
fi

# Load .sofin.env if exists in PWD:
load_sofin_env () {
    if [ -r "$PWD/.sofin.env" ]; then
        source "$PWD/.sofin.env"
    fi
}

# Load local environment when the current working directory changes (zsh):
chpwd() {
    load_sofin_env
}

# Load with shell loads:
load_sofin_env
