#!/Software/Zsh/exports/zsh

unset CC CPP CXX CFLAGS CXXFLAGS LDFLAGS MANPATH PATH PKG_CONFIG_PATH MAIL

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/Software/Subversion/exports

set -e

readonly PARALLEL_JOBS="8"
readonly ARCH="$(uname -m)"
readonly SHARED_DIR="/Jails/Shared"
readonly CONF_FILE="/etc/sofin.conf.sh"
readonly LOG_OUTPUT="/var/log/build-$(date +%F).log"
if [ -e "${CONF_FILE}" ]; then
    . "${CONF_FILE}"
    validate_env
else
    echo "FATAL: No configuration file found: ${CONF_FILE}. Sofin isn't installed properly."
    exit 1
fi

for version in 10.1 9.3; do
    echo "Process started for version: ${version}: $(date +%F@%H-%M)" > ${LOG_OUTPUT}
    note "Process started for version: ${version}: $(date +%F@%H-%M)"
    note "Processing version: ${version}"
    cd /usr
    if [ ! -d "${version}-src" ]; then
        svn co http://svn0.eu.FreeBSD.org/base/releng/${version} ${version}-src
        cd ${version}-src
    else
        cd ${version}-src
        svn up
    fi
    # find ${SHARED_DIR}/FreeBSD-*-${ARCH} -exec chflags -R noschg {} \;
    note "Removing old Jail build for ${version}"
    rm -rfv ${SHARED_DIR}/FreeBSD-${version}-${ARCH} >> ${LOG_OUTPUT}
    note "Preparing new Jail builds"
    mkdir -p ${SHARED_DIR}/FreeBSD-${version}-${ARCH} >> ${LOG_OUTPUT}
    note "Preparing kernel configuration"
    rm -fv /usr/${version}-src/sys/${ARCH}/conf/VERKNOWSYS >> ${LOG_OUTPUT}
    cp -v /var/ServeD-OS/kernel/VERKNOWSYS-${version} /usr/${version}-src/sys/${ARCH}/conf/VERKNOWSYS >> ${LOG_OUTPUT}
    note "Building world"
    make clean >> ${LOG_OUTPUT}
    make buildworld -j${PARALLEL_JOBS} DEBUG= DESTDIR=${SHARED_DIR}/FreeBSD-${version}-${ARCH} >> ${LOG_OUTPUT}  2>&1
    note "Building kernel"
    make buildkernel DEBUG= DESTDIR=${SHARED_DIR}/FreeBSD-${version}-${ARCH} >> ${LOG_OUTPUT} 2>&1
    note "Installing kernel"
    make installkernel DEBUG= DESTDIR=${SHARED_DIR}/FreeBSD-${version}-${ARCH} >> ${LOG_OUTPUT}  2>&1
    note "Installing world"
    make installworld DEBUG= DESTDIR=${SHARED_DIR}/FreeBSD-${version}-${ARCH} >> ${LOG_OUTPUT}  2>&1
    note "Cleaning up"
    rm -vrf ${SHARED_DIR}/FreeBSD-${version}-${ARCH}/{media,mnt,proc,root,sys,etc,dev,rescue,tmp} >> ${LOG_OUTPUT}
    echo "Process finished: $(date +%F@%H-%M)" >> ${LOG_OUTPUT}
    note "Process finished: $(date +%F@%H-%M)"
done
