#!/bin/sh

clear

. build.env

test -x "${SOFIN_BIN}" && \
    ${SOFIN_BIN} disable && \
    echo "Sofin environment disabled"

test -f "${SOFIN_DATA_DIR}/loader" && \
    . "${SOFIN_DATA_DIR}/loader" && \
    echo "Loaded ${SOFIN_DATA_DIR}/loader"


test -f "${BUILD_NUMBER_FILE}" || echo "1" > "${BUILD_NUMBER_FILE}"
export BUILD_NUMBER="$(echo "$(cat "${BUILD_NUMBER_FILE}" 2>/dev/null)+1" | bc 2>/dev/null)"
export VERSION="${VERSION_MAJOR}-${SYSTEM_VERSION}-b${BUILD_NUMBER}"
test -z "${BUILD_NUMBER_FILE}" && exit 122
test -z "${BUILD_NUMBER}" && exit 123
test -z "${VERSION}" && exit 124

echo "BUILD no: ${BUILD_NUMBER}"
echo "${BUILD_NUMBER}" > "${BUILD_NUMBER_FILE}"
echo "Updating current build number on workstation host…"
${SCP_BIN} "${BUILD_NUMBER_FILE}" "${WORKSTATION_USER}@${HOSTADDR_GW}:/Users/${WORKSTATION_USER}/${BUILD_NUM_NAME}"

# ${INSTALL_BIN} -v etc/make.conf /etc/
# ${INSTALL_BIN} -v etc/src.conf /etc/

# test -z "${DEVEL}" && \
#     git reset --hard
case ${ARCH} in
    arm)
        sed -i '' -e 's/^COPTFLAGS.*$/COPTFLAGS=-O2 -pipe -ffast-math -fno-strict-aliasing -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard/' etc/make.conf
        sed -i '' -e 's/^CPUTYPE.*$/CPUTYPE?=armv6/' etc/make.conf
        sed -i '' -e 's/^CFLAGS.*$/CFLAGS=-O2 -pipe -fno-omit-frame-pointer -fno-strict-aliasing -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard/' etc/make.conf
        ;;

    amd64|x86_64)
        ;;

    *)
        echo "Error: Architecture not supported: ${ARCH}"
        exit 1
        ;;
esac

set -e
echo "Pedantic mode enabled!"

. build.env
. build-base

echo "Build #${BUILD_NUMBER} started at: ${TIMESTAMP}"
build_base

set +e
