#!/Software/Zsh/exports/zsh

unset CC CPP CXX CFLAGS CXXFLAGS LDFLAGS MANPATH PATH PKG_CONFIG_PATH MAIL

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/Software/Subversion/exports

set -e

readonly PARALLEL_JOBS="10"
readonly ARCH="$(uname -m)"
readonly SHARED_DIR="/Jails/Shared"
readonly CONF_FILE="/etc/sofin.conf.sh"
readonly LOG_OUTPUT="/var/log/build-$(date +%F).log"
if [ -e "${CONF_FILE}" ]; then
    . "${CONF_FILE}"
    validate_env
else
    echo "FATAL: No configuration file found: ${CONF_FILE}. Sofin isn't installed properly."
    exit 1
fi

if [ ! -d "/var/ServeD-OS" ]; then
    cd /var
    GIT_SSL_NO_VERIFY=true /Software/Git/exports/git clone https://github.com/VerKnowSys/ServeD-OS.git
else
    cd /var/ServeD-OS
    GIT_SSL_NO_VERIFY=true /Software/Git/exports/git pull https://github.com/VerKnowSys/ServeD-OS.git
fi

note "Setting up make.conf"
${RM_BIN} -f /etc/make.conf
${CP_BIN} /var/ServeD-OS/etc/make.conf /etc/make.conf

for version in $(${SOFIN_VERSION_UTILITY_BIN}); do
    echo "Process started for version: ${version}: $(date +%F@%H-%M)" > ${LOG_OUTPUT}
    note "Process started for version: ${version}: $(date +%F@%H-%M)"
    note "Processing version: ${version}"
    rm -f /usr/src
    cd /var
    if [ ! -d "${version}-src" ]; then
        # svn co http://svn0.eu.FreeBSD.org/base/releng/${version} ${version}-src
        /Software/Git/exports/git clone --single-branch --branch hardened/10-stable/master https://github.com/hardenedbsd/hardenedbsd-stable/ ${version}-src
        cd ${version}-src
    else
        cd ${version}-src
        /Software/Git/exports/git pull
    fi
    ln -s /var/${version}-src /usr/src

    TIMESTAMP="$(date +%F-%s)"
    DESTBASE="${SHARED_DIR}/FreeBSD-${version}-${ARCH}"
    DESTDIR="${DESTBASE}-${TIMESTAMP}"

    note "Moving 'current' to 'oldcurrent' for ${version}"
    rm -f ${DESTBASE}.oldversion || true
    mv ${DESTBASE} ${DESTBASE}.oldversion >> ${LOG_OUTPUT}

    note "Preparing new Jail builds for timestamp: ${TIMESTAMP}"
    mkdir -p ${DESTDIR} >> ${LOG_OUTPUT}
    note "Preparing kernel configuration"
    rm -fv /var/${version}-src/sys/${ARCH}/conf/VERKNOWSYS >> ${LOG_OUTPUT}
    cp -v /var/ServeD-OS/kernel/VERKNOWSYS-${version} /var/${version}-src/sys/${ARCH}/conf/VERKNOWSYS >> ${LOG_OUTPUT}

    note "Building world"
    make buildworld -j${PARALLEL_JOBS} DEBUG= DESTDIR=${DESTDIR} >> ${LOG_OUTPUT}  2>&1

    note "Building kernel"
    make buildkernel DESTDIR=${DESTDIR} >> ${LOG_OUTPUT} 2>&1

    note "Installing kernel"
    make installkernel DESTDIR=${DESTDIR} >> ${LOG_OUTPUT}  2>&1

    note "Installing world"
    make installworld DEBUG= DESTDIR=${DESTDIR} >> ${LOG_OUTPUT}  2>&1

    note "Linking current"
    ln -s ${DESTDIR} ${DESTBASE}

    note "Cleaning up"
    rm -vrf ${DESTBASE}/{media,mnt,proc,root,sys,etc,dev,rescue,tmp} >> ${LOG_OUTPUT}
    echo "Process finished: $(date +%F@%H-%M)" >> ${LOG_OUTPUT}
    note "Process finished: $(date +%F@%H-%M)"
done
