#!/bin/sh

set -e

unset CXX
unset CPP
unset CC
unset PKG_CONFIG_PATH
unset MANPATH
unset LDFLAGS
unset CXXFLAGS
unset CFLAGS

# HardenedBSD base branch:
readonly VERSION="$1"
if [ "${VERSION}" = "" ]; then
    echo "No version specified! Specify f.e.: v0.99.10"
    exit 1
fi
readonly OS_VER="11.0" # 10.2
readonly MAIN_REPOSITORY="https://github.com/hardenedbsd/hardenedbsd-stable/"
readonly CURRENT_BRANCH="hardened/current/master" # 10-stable
readonly DESTINATION="dmilith@served.verknowsys.com:/Users/dmilith/ServeD/Web/"
readonly BASE_NAME="ServeD-OS-Base"

# build system base
/bin/sh ./build-jail-base "${OS_VER}" "${MAIN_REPOSITORY}" "${CURRENT_BRANCH}"
/bin/sh ./build-binary-snapshots "${BASE_NAME}" "${VERSION}" "${OS_VER}" "${DESTINATION}"
