#!/usr/bin/env zsh
# ZSH is required
#
# 2014-09-02 13:11:55
# blame: @dmilith

set -e

readonly CONF_FILE="/etc/sofin.conf.sh"
if [ -e "${CONF_FILE}" ]; then
    . "${CONF_FILE}"
    validate_env
else
    echo "FATAL: No configuration file found: ${CONF_FILE}. Sofin isn't installed properly."
    exit 1
fi


readonly NAME="$1"
if [ "${NAME}" = "" ]; then
    error "No name specified!"
fi

readonly VERSION="$2"
if [ "${VERSION}" = "" ]; then
    error "No version specified!"
fi

readonly OS_VER="$3"
if [ "${OS_VER}" = "" ]; then
    error "No OS version specified!"
fi

readonly DESTINATION="$4"
if [ "${DESTINATION}" = "" ]; then
    error "No destination path specified!"
fi

readonly ARCH="$5"
if [ "${ARCH}" = "" ]; then
    error "No architecture specified!"
fi

compile_jails () {
    BASE_SNAPSHOT="${NAME}-${OS_VER}-v${VERSION}-${ARCH}"
    note "Compiling snapshot: ${BASE_SNAPSHOT}"
    REALPATH="/Jails/Shared/FreeBSD-${OS_VER}-${ARCH}"
    tar cfJ ../${BASE_SNAPSHOT}.tar.xz "${REALPATH}" >> /var/log/messages 2>&1
    if [ "$?" = "0" ]; then
        note "Compiled successfully."
    else
        error "Something went wrong while compiling snapshot!"
        exit 1
    fi

    note "Setting snapshot as readable by everyone"
    chmod a+r ../${BASE_SNAPSHOT}.tar.xz

    note "Uploading Jail snapshot: ${BASE_SNAPSHOT}"
    scp ../${BASE_SNAPSHOT}.tar.xz ${DESTINATION}
    if [ "$?" = "0" ]; then
        note "Finished successfully. Updating latest version on remote destination"
        ssh dmilith@served.verknowsys.com "echo '${VERSION}' > /Users/dmilith/ServeD/Web/version-latest"
    else
        error "Something went wrong while uploading Jails base."
        exit 1
    fi
}


compile_jails
