#!/bin/sh

set -e

unset CXX
unset CPP
unset CC
unset PKG_CONFIG_PATH
unset MANPATH
unset LDFLAGS
unset CXXFLAGS
unset CFLAGS

VERSION="$1"
if [ "${VERSION}" = "" ]; then
    echo "No version specified! Specify f.e.: v0.99.10"
    exit 1
fi

/bin/sh ./build-jail-base # TODO: ${VERSION}
/bin/sh ./build-binary-snapshots ${VERSION}
