#!/usr/bin/env zsh
# ZSH is required
#
# 2014-09-02 13:11:55
# blame: @dmilith

readonly CONF_FILE="/etc/sofin.conf.sh"
if [ -e "${CONF_FILE}" ]; then
    . "${CONF_FILE}"
    validate_env
else
    echo "FATAL: No configuration file found: ${CONF_FILE}. Sofin isn't installed properly."
    exit 1
fi

note "Synchronizing time"
ntpdate -u ntp.nask.pl

NAME="ServeD-OS-Base"
VERSION="v0.4.dev"
if [ -f "/VERSION" ]; then
    VERSION="$(cat /VERSION)"
fi
SNAPSHOT="${NAME}-${VERSION}"
SNAPSHOT_JAIL="${NAME}-Jails-${VERSION}"
SNAPSHOT_DIR="/VKS-SNAPSHOTS/${SNAPSHOT}"
DESTINATION="dmilith@verknowsys.com:/home/dmilith/Web/Public/ServeD/"

test -d "${SNAPSHOT_DIR}" && (note "Cleaning up old snapshot from today.." && rm -rf "${SNAPSHOT_DIR}")
mkdir -p "${SNAPSHOT_DIR}"

DIRS=(boot etc usr usr/bin usr/lib usr/include var)
for dir in ${DIRS}; do
    if [ ! -d "${SNAPSHOT_DIR}/${dir}" ]; then
        note "Creating destination dir: ${dir}"
        mkdir -p "${SNAPSHOT_DIR}/${dir}"
    fi
done

note "Cleaning before snapshot"
rm -rf /root/.cache /root/.ccache /root/.npm

note "Updating ServeD-OS repository."
if [ ! -d "/var/ServeD-OS" ]; then
    cd /var
    git clone https://github.com/VerKnowSys/ServeD-OS.git
else
    cd /var/ServeD-OS
    git pull https://github.com/VerKnowSys/ServeD-OS.git
fi

note "Preparing Base snapshot: ${SNAPSHOT}"
cp -v /VERSION "${SNAPSHOT_DIR}"
cp -Rv /Software "${SNAPSHOT_DIR}"
cp -vr /var/ServeD-OS "${SNAPSHOT_DIR}/var"
cp -v /etc/profile* "${SNAPSHOT_DIR}/etc"
cd "${SNAPSHOT_DIR}"

note "Compiling Jails snapshot: ${SNAPSHOT_JAIL}"
tar vcfJ ../${SNAPSHOT_JAIL}.tar.xz /Jails
if [ "$?" = "0" ]; then
    note "Compiled successfully."
else
    error "Something went wrong while compiling Jails Base."
    exit 1
fi

note "Compiling Base snapshot: ${SNAPSHOT}"
tar cfJ ../${SNAPSHOT}.tar.xz ./
if [ "$?" = "0" ]; then
    note "Compiled successfully."
else
    error "Something went wrong while compiling Base."
    exit 1
fi

note "Uploading Base snapshot"
scp ../${SNAPSHOT}.tar.xz ${DESTINATION}
if [ "$?" = "0" ]; then
    note "Finished successfully."
else
    error "Something went wrong while uploading Base snapshot."
    exit 1
fi

note "Uploading Jails snapshot"
scp ../${SNAPSHOT_JAIL}.tar.xz ${DESTINATION}
if [ "$?" = "0" ]; then
    note "Finished successfully."
else
    error "Something went wrong while uploading Jails base."
    exit 1
fi
