#!/bin/sh

SOFIN_VERSION=0.64.2
SYS_ROOT_DOMAIN="verknowsys.com"
SYS_DOMAIN="$(hostname).${SYS_ROOT_DOMAIN}"

test -d /Users && mkdir /Users

freebsd-update fetch
freebsd-update install

if [ ! -x /usr/bin/sofin ]; then
    cd /var
    if [ ! -d "sofin-${SOFIN_VERSION}" ]; then
        fetch http://dmilith.verknowsys.com/Public/Sofin-releases/sofin-${SOFIN_VERSION}.tar.bz2
        tar xf sofin-${SOFIN_VERSION}.tar.bz2
    fi
    cd sofin-${SOFIN_VERSION}
    bin/install
    sofin distclean
fi

if [ "${SHELL}" != "/Software/Zsh/exports/zsh" ]; then
    echo "Setting ZSH shell"
    chsh -s /Software/Zsh/exports/zsh
fi

echo "Setting HOME to /SystemUsers"
pw user mod root -d /SystemUsers

if [ -f "/.vks-snapshot-version" ]; then
    echo "Copying additional system files"
    git clone https://github.com/VerKnowSys/ServeD-OS.git
    cd ServeD-OS
    cp -Rv boot/ /boot/
    cp -Rv etc/ /etc/
    cp -Rv usr/ /usr/
fi

echo "Post-copy: Copying served files if not yet exist"
test -f /etc/ttys || cp -v /etc/ttys.served /etc/ttys
# TODO implement better managment of rest important files

echo "Initializing core system services for domain: ${SYS_DOMAIN}"
test -d /SystemUsers/SoftwareData/Coreginx || mkdir -p /SystemUsers/SoftwareData/Coreginx
test -f /SystemUsers/SoftwareData/Coreginx/.running || touch /SystemUsers/SoftwareData/Coreginx/.start
test -f /SystemUsers/SoftwareData/Coreginx/.domains/${SYS_DOMAIN} || (mkdir -p /SystemUsers/SoftwareData/Coreginx/.domains ; touch /SystemUsers/SoftwareData/Coreginx/.domains/${SYS_DOMAIN} && touch /SystemUsers/SoftwareData/Coreginx/.reconfigure)

test -d /SystemUsers/SoftwareData/Ntp || mkdir -p /SystemUsers/SoftwareData/Ntp
test -f /SystemUsers/SoftwareData/Ntp/.running || touch /SystemUsers/SoftwareData/Ntp/.start

test -d /SystemUsers/SoftwareData/LiveUsers || mkdir -p /SystemUsers/SoftwareData/LiveUsers
test -f /SystemUsers/SoftwareData/LiveUsers/.running || touch /SystemUsers/SoftwareData/LiveUsers/.start

echo "Reloading core services"
kill -SIGHUP 1
