#!/bin/sh
#
# @author Daniel (dmilith) Dettaff
#
# TODO: gvr copy-attrs sourcejailname destjailname

. /Software/Sofin/share/loader

GVR_VERSION="0.22.0"
GVR_LOG="/var/log/gvr.log"
ORIGIN="origin"
KERN_SECURELEVEL="0"
# XXX: hardcoded:
JAIL_ROUTER_ADDRESS="100.64.1.1"
BRIDGE_DEVICE="bridge0"
EPAIR_DEVICE="epair"
SERVED_REPO="/Projects/svdOS"
SOFIN_REPO="/Projects/Sofin"
DEFAULT_SOFIN_REPO="https://github.com/VerKnowSys/sofin.git"
# SERVICE_SPAWNER_BIN="/Software/Thess/exports/svdss"
# IGNITER_INSTALL_BIN="/Software/Thess/exports/ignitersinstall"
SH_BIN="/bin/sh"
JOT_BIN="/usr/bin/jot"
IFCONFIG_BIN="/sbin/ifconfig"
JEXEC_BIN="/usr/sbin/jexec"
ROUTE_BIN="/sbin/route"
RCTL_BIN="/usr/bin/rctl"
GMAKE_BIN="/Software/Make/bin/make"
DEFAULT_ZPOOL="zroot"
DEFAULT_VERSION="11.2"
DEFAULT_ARCH="amd64"
DEFAULT_SHELL="/Software/Zsh/exports/zsh"
LOG="${LOGS_DIR}gvr.log"
# stored_version="$(${ZFS_BIN} get -H -o value com.svd:os_version ${DEFAULT_ZPOOL}/ROOT)"
# if [ "${stored_version}" != "-" ]; then
#     DEFAULT_VERSION="${stored_version}"
# fi
DEFAULT_JAIL_USER="www"
DEFAULT_QUOTA_LIMIT="10G"
DEFAULT_ROOT_QUOTA_LIMIT="2G"
DEFAULT_SENTRY_LIMIT="128M"
DEFAULT_LIMIT_MAX_MEMORY="512M"
DEFAULT_LIMIT_MAX_VMEMORY="1024M"
DEFAULT_LIMIT_MAXPROC="64"
DEFAULT_LIMIT_OPENFILES="16384" # this is required f.e. for Postgresql to work properly
DEFAULT_LIMIT_MAXPTS="16"
DEFAULT_JAIL_SHARED_LOCATION="/Shared"
DEFAULT_CELLS_LOCATION="${DEFAULT_JAIL_SHARED_LOCATION}/Prison/Cells"
DEFAULT_SENTRY_LOCATION="${DEFAULT_JAIL_SHARED_LOCATION}/Prison/Sentry"
CELL_IP_ADDRESSES_ATTRIBUTE="jail.ip.addresses"
CELL_OS_VERSION_ATTRIBUTE="jail.os.version"
CELL_EPAIR_NUMBER_ATTRIBUTE="jail.vlan.number"
CELL_ATTRIBUTES_DIR="jail-attributes"
CELL_DOMAINS_DIR="jail-domains"
CELL_WEBCONF_DIR="jail-webconfs"
CELL_LOGS_DIR="jail-loggers"
JAIL_CONF_NAME="jail.conf"
JAIL_TRUSS_NAME="jail.truss.log"
JAIL_TRUSS_EXEC_NAME="jail.truss.exec.log"
JAIL_ID_NAME="jail.id"
JAIL_STATUS_NAME="jail.status"
JAIL_RUNNING_INDICATOR="jail.running"
DEFAULT_HOST_ADDRESS="/etc/host.default"
DEFAULT_JAILS_FIB="0"
DEFAULT_UNAME="FreeBSD"
GVR_SCRIPT_NAME="$(${BASENAME_BIN} "${0}" 2>/dev/null)"
DEFAULT_INTERFACE="$(${ROUTE_BIN} show -net 0 2>/dev/null | ${TAIL_BIN} -n 4 2>/dev/null | ${HEAD_BIN} -n1 2>/dev/null | ${AWK_BIN} '{print $2;}' 2>/dev/null)"
GVR_HOST_IP_ADDR="$(${IFCONFIG_BIN} "${DEFAULT_INTERFACE}" 2>/dev/null | ${GREP_BIN} -v grep 2>/dev/null | ${GREP_BIN} inet 2>/dev/null | ${AWK_BIN} '{print $2;}' 2>/dev/null)"
if [ -z "${DEFAULT_INTERFACE}" ]; then
    error "Something is wrong with network routing configuration. Governor can't continue on this host"
fi
DEFAULT_JAIL_ETC_SOURCE="${SERVED_REPO}/etc-jail/"
if [ ! -d "${DEFAULT_JAIL_ETC_SOURCE}" ]; then
    error "Sanity check failed: Could not found etc source location: ${DEFAULT_JAIL_ETC_SOURCE}. Governor can't continue"
fi

# Create default jail sentry and cells location
if [ ! -d "${DEFAULT_JAIL_SHARED_LOCATION}" ]; then
    # No deduplication on /Shared
    try "${ZFS_BIN} create -o dedup=off -o mountpoint=none ${DEFAULT_ZPOOL}${DEFAULT_JAIL_SHARED_LOCATION}"
fi
if [ ! -d "${DEFAULT_JAIL_SHARED_LOCATION}/Prison" ]; then
    # No deduplication on /Shared/Prison
    try "${ZFS_BIN} create -o dedup=off -o mountpoint=none ${DEFAULT_ZPOOL}${DEFAULT_JAIL_SHARED_LOCATION}/Prison"
fi

if [ ! -d "${DEFAULT_SENTRY_LOCATION}" ]; then
    # Deduplication on /Sentry
    try "${ZFS_BIN} create -o dedup=on -o mountpoint=none ${DEFAULT_ZPOOL}${DEFAULT_SENTRY_LOCATION}"
fi
if [ ! -d "${DEFAULT_CELLS_LOCATION}" ]; then
    # Deduplication on /Cells
    try "${ZFS_BIN} create -o dedup=on -o mountpoint=none ${DEFAULT_ZPOOL}${DEFAULT_CELLS_LOCATION}"
fi

DEFAULT_JAIL_SYSTEM_PATH="${DEFAULT_JAIL_SHARED_LOCATION}/${DEFAULT_UNAME}-${DEFAULT_VERSION}-${DEFAULT_ARCH}"
if [ ! -d "${DEFAULT_JAIL_SYSTEM_PATH}" ]; then
    SOURCE="http://software.verknowsys.com/binary/ServeD"
    JAIL_CACHE_DIR="${DEFAULT_JAIL_SHARED_LOCATION}/Cache"
    mkdir -p "${JAIL_CACHE_DIR}"
    fetch "${SOURCE}/current-stable" -o "${JAIL_CACHE_DIR}/current-stable"
    CURRENT_VERSION="$(cat "${JAIL_CACHE_DIR}/current-stable" 2>/dev/null)"
    if [ -n "${CURRENT_VERSION}" ]; then
        if [ ! -f "${JAIL_CACHE_DIR}/${CURRENT_VERSION}" ]; then
            note "Fetching ServeD stable version: ${CURRENT_VERSION} as jail base system resource: ${DEFAULT_ZPOOL}${DEFAULT_JAIL_SYSTEM_PATH}"
            fetch "${SOURCE}/${CURRENT_VERSION}" -o "${JAIL_CACHE_DIR}/${CURRENT_VERSION}"
        else
            note "ServeD stable already fetched."
        fi

        zfs list "${DEFAULT_ZPOOL}${DEFAULT_JAIL_SYSTEM_PATH}" >/dev/null || \
            {
                lz4cat "${JAIL_CACHE_DIR}/${CURRENT_VERSION}" 2>/dev/null | zfs receive -u "${DEFAULT_ZPOOL}${DEFAULT_JAIL_SYSTEM_PATH}";
                zfs snapshot "${DEFAULT_ZPOOL}${DEFAULT_JAIL_SYSTEM_PATH}@origin";
            }
    fi
fi

# This is where all jail settings are put into global scope of script:
set_values () {
    ENTERED_NAME="${1}"
    if [ -z "${ENTERED_NAME}" ]; then
        error "Empty cell name!"
    fi
    CELL="${DEFAULT_CELLS_LOCATION}/${ENTERED_NAME}"
    SENTRY="${DEFAULT_SENTRY_LOCATION}/${ENTERED_NAME}"
    debug "Processing CELL: ${CELL}, Sentry: ${SENTRY}"
    JAIL_DOMAINS_DIR="${SENTRY}/${CELL_DOMAINS_DIR}"
    JAIL_CONF_FILE="${SENTRY}/${JAIL_CONF_NAME}"
    JAIL_ATTRIBUTES_DIR="${SENTRY}/${CELL_ATTRIBUTES_DIR}"
    JAIL_NAME="$(printf "${ENTERED_NAME}\n" | ${SED_BIN} 's/\./-/g' 2>/dev/null)"
    JAIL_ID_FILE="${SENTRY}/${JAIL_ID_NAME}"
    JAIL_TRACE_LOG="${SENTRY}/${JAIL_TRUSS_NAME}"
    JAIL_EXEC_LOG="${SENTRY}/${JAIL_TRUSS_EXEC_NAME}"
    DEBUG_COMMAND=""
    DEBUG_EXEC_COMMAND=""
    if [ "${DEBUG}" = "truss" ]; then
        DEBUG_COMMAND="${TRUSS_BIN} -o ${JAIL_TRACE_LOG}"
        DEBUG_EXEC_COMMAND="${TRUSS_BIN} -o ${JAIL_EXEC_LOG}"
    fi
    JAIL_EPAIR_NUMBER_FILE="${SENTRY}/${CELL_EPAIR_NUMBER_ATTRIBUTE}"
    JAIL_VERSION_FILE="${SENTRY}/${CELL_OS_VERSION_ATTRIBUTE}"
    JAIL_ADDRESSES_FILE="${SENTRY}/${CELL_IP_ADDRESSES_ATTRIBUTE}"
    JAIL_WEBSERVER_CONF_DIR="${SENTRY}/${CELL_WEBCONF_DIR}"
    JAIL_LOGS_CONF_DIR="${SENTRY}/${CELL_LOGS_DIR}"
    JAIL_STATUS_FILE="${SENTRY}/${JAIL_STATUS_NAME}"
    JAIL_STATUS_DETAIL=""
    if [ -f "${JAIL_STATUS_FILE}" ]; then
        JAIL_STATUS_DETAIL="$(${CAT_BIN} "${JAIL_STATUS_FILE}" 2>/dev/null)"
    fi
    JAIL_STATUS="${red}*off*${gray} ${JAIL_STATUS_DETAIL}${reset}"
    ${JLS_BIN} -v 2>/dev/null | ${EGREP_BIN} "${JAIL_NAME} .*ACTIVE" >/dev/null 2>&1
    if [ "$?" = "0" ]; then
        JAIL_STATUS="${green}*on*${gray} ${JAIL_STATUS_DETAIL}${reset}"
    fi
    debug "Got jail status: ${JAIL_STATUS}"
    JAIL_VERSION="${DEFAULT_VERSION}"
    if [ -f "${JAIL_VERSION_FILE}" ]; then
        JAIL_VERSION="$(${CAT_BIN} "${JAIL_VERSION_FILE}" 2>/dev/null)"
    fi
    if [ -f "${JAIL_EPAIR_NUMBER_FILE}" ]; then
        EPAIR_NUMBER="$(${CAT_BIN} "${JAIL_EPAIR_NUMBER_FILE}" 2>/dev/null)"
    fi
    debug "Got jail os version: ${JAIL_VERSION}"
    JAIL_SOURCE="${DEFAULT_JAIL_SHARED_LOCATION}/${SYSTEM_NAME}-${JAIL_VERSION}-${SYSTEM_ARCH}"
    debug "Got jail source: ${JAIL_SOURCE}"
    if [ -f "${JAIL_ADDRESSES_FILE}" ]; then
        JAIL_IPS="$(${CAT_BIN} "${JAIL_ADDRESSES_FILE}" 2>/dev/null)"
    fi
    debug "Got jail IP(s): ${JAIL_IPS}"
    HOSTNAMES=""
    for hostnfile in $(${FIND_BIN} "${JAIL_DOMAINS_DIR}" -type f 2>> "${GVR_LOG}"); do
        hostn="$(${CAT_BIN} "${hostnfile}" 2>/dev/null | ${GREP_BIN} "local-zone:" 2>/dev/null | ${SED_BIN} 's/^.* "//;s/.".*//' 2>/dev/null)"
        debug "hostn: ${hostn}"
        HOSTNAMES="*.${hostn} ${HOSTNAMES}"
    done
    debug "Got jail hostnames: ${HOSTNAMES}"
    JAIL_LOCAL_DOMAIN_CONF="${JAIL_DOMAINS_DIR}/local.conf"
}


show_version () {
    note "GoVeRnor: ${cyan}v${GVR_VERSION}${reset}"
}


check_cell_name () {
    GIVEN_NAME="${1}"
    NAME="$(${BASENAME_BIN} "${GIVEN_NAME}" 2>/dev/null)"
    if [ ! -d "${GIVEN_NAME}" ]; then
        error "Bad jail name: ${NAME}"
    fi
}


apply_attributes () {
    run "${RCTL_BIN} -a jail:${JAIL_NAME}:memoryuse:deny=${DEFAULT_LIMIT_MAX_MEMORY}" && \
    run "${RCTL_BIN} -a jail:${JAIL_NAME}:vmemoryuse:deny=${DEFAULT_LIMIT_MAX_VMEMORY}" && \
    run "${RCTL_BIN} -a jail:${JAIL_NAME}:maxproc:deny=${DEFAULT_LIMIT_MAXPROC}" && \
    run "${RCTL_BIN} -a jail:${JAIL_NAME}:openfiles:deny=${DEFAULT_LIMIT_OPENFILES}" && \
    run "${RCTL_BIN} -a jail:${JAIL_NAME}:pseudoterminals:deny=${DEFAULT_LIMIT_MAXPTS}" && \
        note "Applied default attributes for jail: ${cyan}${JAIL_NAME}"

    debug "Applying attributes from location: ${JAIL_ATTRIBUTES_DIR} for jail: ${JAIL_NAME}"
    ${MKDIR_BIN} -p "${JAIL_DOMAINS_DIR}" "${JAIL_ATTRIBUTES_DIR}" "${JAIL_WEBSERVER_CONF_DIR}" "${JAIL_LOGS_CONF_DIR}"
    cd "${JAIL_ATTRIBUTES_DIR}"
    for attribute in $(${LS_BIN} 2>/dev/null); do
        value="$(${CAT_BIN} "${JAIL_ATTRIBUTES_DIR}/${attribute}" 2>/dev/null)"
        debug "Attribute: ${attribute}, value: ${value}"
        case "${attribute}" in
            key)
                a_key="ssh-ed25519 ${value} ${JAIL_NAME}\n"
                ${JEXEC_BIN} -U "${DEFAULT_JAIL_USER}" "${JAIL_NAME}" "${DEFAULT_SHELL}" -c "${MKDIR_BIN} -p /User/.ssh; printf '${a_key}' >> /User/.ssh/authorized_keys"
                ${JEXEC_BIN} -U "${DEFAULT_JAIL_USER}" "${JAIL_NAME}" "${DEFAULT_SHELL}" -c "${CHOWN_BIN} -R ${DEFAULT_JAIL_USER} /User/.ssh"
                ;;

            ip)
                note "Setting IPs: ${cyan}${value}${green} for jail: ${cyan}${JAIL_NAME}"
                debug "conf: ${DEFAULT_SENTRY_LOCATION}/${JAIL_NAME}/${CELL_IP_ADDRESSES_ATTRIBUTE}"
                printf "${value}" > "${DEFAULT_SENTRY_LOCATION}/${JAIL_NAME}/${CELL_IP_ADDRESSES_ATTRIBUTE}"
                ${SED_BIN} -i '' -e "s#ip4\.addr.*;\$#ip4.addr = ${value};#" "${JAIL_CONF_FILE}"
                ${RM_BIN} -f "${JAIL_ATTRIBUTES_DIR}/${attribute}"
                ;;

            +ip)
                file_size="$(${STAT_BIN} -f%z "${DEFAULT_SENTRY_LOCATION}/${JAIL_NAME}/${CELL_IP_ADDRESSES_ATTRIBUTE}" 2>/dev/null)"
                if [ "${file_size}" -gt "0" ]; then
                    printf ",${value}" >> "${DEFAULT_SENTRY_LOCATION}/${JAIL_NAME}/${CELL_IP_ADDRESSES_ATTRIBUTE}"
                    current_value="$(${CAT_BIN} "${DEFAULT_SENTRY_LOCATION}/${JAIL_NAME}/${CELL_IP_ADDRESSES_ATTRIBUTE}" 2>/dev/null | ${TR_BIN} '\n' ',' 2>/dev/null | ${SED_BIN} -E 's/[,]{2,}/,/g;s/,$//;s/^[,]{1,}//g' 2>/dev/null)"
                    debug "Current value: ${current_value}"
                    ${SED_BIN} -i '' -e "s#ip4\.addr.*;\$#ip4.addr = ${current_value};#" "${JAIL_CONF_FILE}"
                fi
                ${RM_BIN} -f "${JAIL_ATTRIBUTES_DIR}/${attribute}"
                ;;

            quota-root)
                note "Setting root dir quota of: ${cyan}${value}${green} to: ${cyan}${DEFAULT_ZPOOL}${CELL}"
                run "${ZFS_BIN} set quota=${value} ${DEFAULT_ZPOOL}${CELL}"
                ;;

            quota)
                note "Setting quota of: ${value} to ${DEFAULT_ZPOOL}/*/${JAIL_NAME}"
                for dest in Software Services User; do
                    run "${ZFS_BIN} set quota=${value} ${DEFAULT_ZPOOL}/${dest}/${JAIL_NAME}"
                done
                ;;

            quota-software)
                note "Setting quota of: ${cyan}${value}${green} to: ${cyan}${DEFAULT_ZPOOL}/Software/${JAIL_NAME}"
                run "${ZFS_BIN} set quota=${value} ${DEFAULT_ZPOOL}/Software/${JAIL_NAME}"
                ;;

            quota-services)
                note "Setting quota of: ${cyan}${value}${green} to: ${cyan}${DEFAULT_ZPOOL}/Services/${JAIL_NAME}"
                run "${ZFS_BIN} set quota=${value} ${DEFAULT_ZPOOL}/Services/${JAIL_NAME}"
                ;;

            quota-user)
                note "Setting quota of: ${cyan}${value}${green} to: ${cyan}${DEFAULT_ZPOOL}/User/${JAIL_NAME}"
                run "${ZFS_BIN} set quota=${value} ${DEFAULT_ZPOOL}/User/${JAIL_NAME}"
                ;;

            *)
                ${RCTL_BIN} -a "jail:${JAIL_NAME}:${attribute}:deny=${value}" >> "${GVR_LOG}" 2>&1
                if [ "$?" = "0" ]; then
                    note "Overriden attribute: ${cyan}${attribute}${green} with value: ${cyan}${value}"
                else
                    warn "Wrong attribute: ${red}${attribute}"
                fi
                ;;

        esac
    done
}


check_jail_address () {
    JAIL_ADDRESS_CHECK="${1}"
    for jail in $(${LS_BIN} ${DEFAULT_SENTRY_LOCATION} 2>/dev/null); do
        IP_FILE="${DEFAULT_SENTRY_LOCATION}/${jail}/${CELL_IP_ADDRESSES_ATTRIBUTE}"
        if [ -f "${IP_FILE}" ]; then
            for ip in $(${CAT_BIN} "${IP_FILE}" 2>/dev/null | ${TR_BIN} ',' '\n' 2>/dev/null); do
                JAIL_ADDRESS_CHECK=$(printf "${JAIL_ADDRESS_CHECK}" | ${TR_BIN} ',' '\n' 2>/dev/null)
                for addrchk in ${JAIL_ADDRESS_CHECK}; do
                    echo "${ip}" | ${GREP_BIN} "${addrchk}" > /dev/null 2>&1
                    if [ "$?" = "0" ]; then
                        error "Address: ${addrchk} is already assigned to jail: ${jail}"
                    fi
                done
            done
        fi
    done
}


check_jail_name () {
    GIVEN_NAME="${1}"
    for jail in $(${LS_BIN} ${DEFAULT_SENTRY_LOCATION} 2>/dev/null); do
        if [ "${jail}" = "${GIVEN_NAME}" ]; then
            error "Name: ${GIVEN_NAME} is already used"
        fi
    done
}


attributes_show () {
    # NOTE: resources, taken from FreeBSD "rctl" man page:
    note "Attributes with description:"
    printf "   ${cyan}pcpu${gray}: ${green}CPU percentage${reset}\n"
    printf "   ${cyan}cputime${gray}: ${green}CPU time, in seconds${reset}\n"
    printf "   ${cyan}datasize${gray}: ${green}data size, in bytes${reset}\n"
    printf "   ${cyan}stacksize${gray}: ${green}stack size, in bytes${reset}\n"
    printf "   ${cyan}coredumpsize${gray}: ${green}core dump size, in bytes${reset}\n"
    printf "   ${cyan}memoryuse${gray}: ${green}resident set size, in bytes${reset}\n"
    printf "   ${cyan}memorylocked${gray}: ${green}locked memory, in bytes${reset}\n"
    printf "   ${cyan}maxproc${gray}: ${green}number of processes${reset}\n"
    printf "   ${cyan}openfiles${gray}: ${green}file descriptor table size${reset}\n"
    printf "   ${cyan}vmemoryuse${gray}: ${green}address space limit, in bytes${reset}\n"
    printf "   ${cyan}pseudoterminals${gray}: ${green}number of PTYs${reset}\n"
    printf "   ${cyan}swapuse${gray}: ${green}swap usage, in bytes${reset}\n"
    printf "   ${cyan}nthr${gray}: ${green}number of threads${reset}\n"
    printf "   ${cyan}msgqqueued${gray}: ${green}number of queued SysV messages${reset}\n"
    printf "   ${cyan}msgqsize${gray}: ${green}SysV message queue size, in bytes${reset}\n"
    printf "   ${cyan}nmsgq${gray}: ${green}number of SysV message queues${reset}\n"
    printf "   ${cyan}nsem${gray}: ${green}number of SysV semaphores${reset}\n"
    printf "   ${cyan}nsemop${gray}: ${green}number of SysV semaphores modified in a single semop(2) call${reset}\n"
    printf "   ${cyan}nshm${gray}: ${green}number of SysV shared memory segments${reset}\n"
    printf "   ${cyan}shmsize${gray}: ${green}SysV shared memory size, in bytes${reset}\n"
    printf "   ${cyan}wallclock${gray}: ${green}wallclock time, in seconds${reset}\n"
    printf "   ${cyan}quota${gray}: ${green}quota value for /Services, /User and /Software datasets (fmt: 1G 512M 128K). ${reset}\n"
    printf "   ${cyan}quota-services${gray}: ${green}quota value for /Services dataset only (fmt: 1G 512M 128K). ${reset}\n"
    printf "   ${cyan}quota-user${gray}: ${green}quota value for /User dataset only (fmt: 1G 512M 128K). ${reset}\n"
    printf "   ${cyan}quota-software${gray}: ${green}quota value for /Software dataset only (fmt: 1G 512M 128K). ${reset}\n"
    printf "   ${cyan}quota-root${gray}: ${green}quota value for jail base (/) system dataset only (fmt: 1G 512M 128K)${reset}\n"
    printf "   ${cyan}key${gray}: ${green}SSH public key (Skip public key header and comment parts) to be added to authorized keys of jail${reset}\n"
    printf "   ${cyan}ip${gray}: ${green}change jail IP addresses (comma separated) [requires jail restart]${reset}\n"
    printf "   ${cyan}+ip${gray}: ${green}adds specified (comma separated) IP addresses to jail [requires jail restart]${reset}\n"
}


mark_running () {
    printf "$(${DATE_BIN} +%F-%H%M%S 2>/dev/null)\n" > "${SENTRY}/${JAIL_RUNNING_INDICATOR}"
}


jail_create () {
    usage () {
        note "Usage: ${cyan}${GVR_SCRIPT_NAME} create myname IP/Netmask,IP2/Netmask(, … )"
        note
    }
    GIVEN_NAME="${1}"
    if [ -z "${GIVEN_NAME}" ]; then
        usage
        error "No jail name given"
    fi
    check_jail_name "${GIVEN_NAME}"
    JAIL_ADDRESSES="${2}"
    if [ "${JAIL_ADDRESSES}" = "" ]; then
        usage
        error "No ip given"
    fi
    check_jail_address "${JAIL_ADDRESSES}"

    JAIL_VERSION="${3}"
    if [ "${JAIL_VERSION}" = "" ]; then
        JAIL_VERSION="${DEFAULT_VERSION}"
    fi

    EPAIR_NUMBER="$(${JOT_BIN} -r 1 10 4090 2>/dev/null)" # pick Random vlan Number between 10 and 4090
    EPAIR="${EPAIR_DEVICE}${EPAIR_NUMBER}"
    ${IFCONFIG_BIN} "${EPAIR}" > /dev/null 2>&1
    while [ "$?" = "0" ]; do
        EPAIR_NUMBER="$(${JOT_BIN} -r 1 10 4090 2>/dev/null)"
        run "${IFCONFIG_BIN} ${EPAIR}" && \
            note "Picked network vlan: ${EPAIR}"
    done

    set_values "${GIVEN_NAME}"

    run "${ZFS_BIN} create -o mountpoint=${SENTRY} ${DEFAULT_ZPOOL}${SENTRY}" && \
    run "${ZFS_BIN} set quota=${DEFAULT_SENTRY_LIMIT} ${DEFAULT_ZPOOL}${SENTRY}" && \
        note "Mounted and set sentry"

    if [ -f "${JAIL_CONF_FILE}" ]; then
        warn "Jail already configured"
    else
        ADDRESSES_LIST="$(echo "${JAIL_ADDRESSES}" | ${TR_BIN} ',' '\n' 2>/dev/null)"
        if [ -z "${ADDRESSES_LIST}" ]; then
            error "Addresses list can't be empty!"
        fi
        # note "Configuring jail for addresses: ${cyan}${JAIL_ADDRESSES}"
        # run "${IFCONFIG_BIN} ${EPAIR} create" && \
        # run "${IFCONFIG_BIN} ${EPAIR} ${EPAIR_DEVICE} ${EPAIR_NUMBER} vlandev ${DEFAULT_INTERFACE}" && \
        # if [ "${ip}" != "${ADDRESSES_LIST}" ]; then
        #     for ip in ${ADDRESSES_LIST}; do
        #         run "${IFCONFIG_BIN} ${EPAIR} ${ip} alias" || \
        #         warn "Failed to alias to IP: ${ip} on dev: ${EPAIR}"
        #     done
        # fi

        printf "
${JAIL_NAME} {
    # name = \"${JAIL_NAME}\";
    exec.fib = ${DEFAULT_JAILS_FIB};
    exec.prestart += \"${IFCONFIG_BIN} ${EPAIR} create up; ${IFCONFIG_BIN} ${EPAIR}a up; ${IFCONFIG_BIN} ${BRIDGE_DEVICE} addm ${EPAIR}a up;\";
    exec.start  = \"${IFCONFIG_BIN} lo0 127.0.0.1 up\";
    exec.start  += \"${IFCONFIG_BIN} ${EPAIR}b up\";
    exec.start  += \"${IFCONFIG_BIN} ${EPAIR}b inet ${JAIL_ADDRESSES} up\";
    exec.start  += \"${ROUTE_BIN} add default ${JAIL_ROUTER_ADDRESS}\";
    exec.start  += \"${SH_BIN} /etc/rc\";
    exec.stop = \"${SH_BIN} /etc/rc.shutdown\";
    exec.poststop  = \"${IFCONFIG_BIN} ${BRIDGE_DEVICE} deletem ${EPAIR}a\";
    exec.poststop  += \"${IFCONFIG_BIN} ${EPAIR}a destroy\";
    exec.clean;

    host.hostname = \"${JAIL_NAME}\";
    path = \"${CELL}\";

    enforce_statfs = 1;
    allow.mount = 1;
    allow.mount.zfs = 1;
    allow.mount.nullfs = 1;
    allow.mount.tmpfs = 1;
    allow.raw_sockets = 1;
    allow.sysvipc = 1;
    mount.devfs;

    persist;
    vnet;
    vnet.interface  = \"${EPAIR}b\";
}
" >> "${JAIL_CONF_FILE}"
    fi

    LAST=""
    DEFAULT_JAILS_ROOT_DIR="${DEFAULT_JAIL_SHARED_LOCATION}/${SYSTEM_NAME}-${DEFAULT_VERSION}-${SYSTEM_ARCH}"
    note "Looking for snapshots of ${DEFAULT_JAILS_ROOT_DIR}"
    ${ZFS_BIN} list -t snap 2>/dev/null | ${EGREP_BIN} "${SYSTEM_NAME}-${DEFAULT_VERSION}-${SYSTEM_ARCH}@[a-z0-9_-]" > /dev/null 2>&1
    if [ "$?" = "0" ]; then
        LAST="$(${ZFS_BIN} list -H -S creation -t snap -o name 2>/dev/null | ${EGREP_BIN} "${SYSTEM_NAME}-${DEFAULT_VERSION}-${SYSTEM_ARCH}@[a-z0-9_-]" 2>/dev/null | ${SED_BIN} 's/.*@//;s/ .*//' | ${HEAD_BIN} -n 1 2>/dev/null)"
        note "Last snapshot of: ${cyan}${SYSTEM_NAME}-${DEFAULT_VERSION}-${SYSTEM_ARCH} ${green}is: ${cyan}${LAST}"
    fi
    if [ -z "${LAST}" ]; then
        LAST="origin"
        run "${ZFS_BIN} snapshot ${DEFAULT_ZPOOL}${DEFAULT_JAILS_ROOT_DIR}@${LAST}" && \
        warn "No snapshots found of base: '${DEFAULT_ZPOOL}${DEFAULT_JAILS_ROOT_DIR}'. Created origin snapshot"
    fi

    run "${ZFS_BIN} clone ${DEFAULT_ZPOOL}${DEFAULT_JAILS_ROOT_DIR}@${LAST} ${DEFAULT_ZPOOL}${CELL}" && \
        permnote "Cloned last jail system base: ${cyan}${DEFAULT_ZPOOL}${DEFAULT_JAILS_ROOT_DIR}@${LAST}${green} to: ${cyan}${CELL}"

    mst_recent_soft="$(${ZFS_BIN} list -H -S creation -t snap -o name 2>/dev/null | ${EGREP_BIN} "${DEFAULT_ZPOOL}/Software/root@[Pa-z0-9_-]" 2>/dev/null | ${SED_BIN} 's/.*@//;s/ .*//' | ${HEAD_BIN} -n 1 2>/dev/null)"
    ${ZFS_BIN} list -t snap | ${GREP_BIN} "${DEFAULT_ZPOOL}/Software/root@${mst_recent_soft}" > /dev/null 2>&1
    if [ "$?" != "0" ]; then
        error "Something went wrong. Missing origin snapshot: '${DEFAULT_ZPOOL}/Software/root@${mst_recent_soft}'. Aborting"
    else
        note "Found an origin snapshot of: ${cyan}${DEFAULT_ZPOOL}/Software/root@${mst_recent_soft}"
    fi
    {
        note "Cloning: ${cyan}${DEFAULT_ZPOOL}/Software/${JAIL_NAME} ${green}from most recent snapshot: ${cyan}${DEFAULT_ZPOOL}/Software/root@${mst_recent_soft}";
        run "${ZFS_BIN} clone ${DEFAULT_ZPOOL}/Software/root@${mst_recent_soft} ${DEFAULT_ZPOOL}/Software/${JAIL_NAME}";
        run "${ZFS_BIN} clone ${DEFAULT_ZPOOL}/Software/root/Git@origin ${DEFAULT_ZPOOL}/Software/${JAIL_NAME}/Git";
        run "${ZFS_BIN} clone ${DEFAULT_ZPOOL}/Software/root/Zsh@origin ${DEFAULT_ZPOOL}/Software/${JAIL_NAME}/Zsh";
    }

    for dset in Software Services User Shared; do
        ${ZFS_BIN} list 2>/dev/null | ${EGREP_BIN} "${DEFAULT_ZPOOL}/${dset}/${JAIL_NAME}" >/dev/null 2>&1 || \
        run "${ZFS_BIN} create -p ${DEFAULT_ZPOOL}/${dset}/${JAIL_NAME}"
        run "${ZFS_BIN} set dedup=on ${DEFAULT_ZPOOL}/${dset}/${JAIL_NAME}" && \
        run "${ZFS_BIN} set checksum=fletcher4 ${DEFAULT_ZPOOL}/${dset}/${JAIL_NAME}" && \
        run "${ZFS_BIN} set aclinherit=passthrough ${DEFAULT_ZPOOL}/${dset}/${JAIL_NAME}" && \
        run "${ZFS_BIN} set aclmode=passthrough ${DEFAULT_ZPOOL}/${dset}/${JAIL_NAME}" && \
        run "${ZFS_BIN} set canmount=off ${DEFAULT_ZPOOL}/${dset}/${JAIL_NAME}" && \
        run "${ZFS_BIN} set mountpoint=none ${DEFAULT_ZPOOL}/${dset}" && \
        run "${ZFS_BIN} set mountpoint=/${dset} ${DEFAULT_ZPOOL}/${dset}/${JAIL_NAME}" && \
        run "${ZFS_BIN} set quota=${DEFAULT_QUOTA_LIMIT} ${DEFAULT_ZPOOL}/${dset}/${JAIL_NAME}" && \
        run "${ZFS_BIN} allow -u ${DEFAULT_JAIL_USER} xattr,atime,casesensitivity,checksum,copies,logbias,primarycache,secondarycache,snapdir,userused,dedup,mountpoint,canmount,userprop,create,destroy,snapshot,rollback,clone,promote,rename,mount,send,receive,reservation,readonly ${DEFAULT_ZPOOL}/${dset}/${JAIL_NAME}" && \
        note "Dataset configured: ${cyan}${DEFAULT_ZPOOL}/${dset}/${JAIL_NAME}"
    done
    run "${ZFS_BIN} set quota=${DEFAULT_ROOT_QUOTA_LIMIT} ${DEFAULT_ZPOOL}${CELL}"
    run "${ZFS_BIN} set mountpoint=${CELL} ${DEFAULT_ZPOOL}${CELL}"

    note "Making required jail directories and user dir"
    ${MKDIR_BIN} -p "${JAIL_WEBSERVER_CONF_DIR}" \
                    "${JAIL_ATTRIBUTES_DIR}" \
                    "${JAIL_DOMAINS_DIR}" \
                    "${JAIL_LOGS_CONF_DIR}" \
                    "${CELL}/tmp" \
                    "${CELL}/dev" \
                    "${CELL}/var/log" \
                    "${CELL}/var/tmp" \
                    "${CELL}/SystemUsers" \
                    "${CELL}/Software" \
                    "${CELL}/Services" \
                    "${CELL}/Shared" \
                    "${CELL}/User"

    if [ ! -f "${JAIL_EPAIR_NUMBER_FILE}" ]; then
        printf "${EPAIR_NUMBER}\n" > "${JAIL_EPAIR_NUMBER_FILE}"
    fi
    if [ ! -f "${JAIL_VERSION_FILE}" ]; then
        printf "${JAIL_VERSION}\n" > "${JAIL_VERSION_FILE}"
    fi
    printf "${JAIL_ADDRESSES}\n" >> "${JAIL_ADDRESSES_FILE}"

    run "${CP_BIN} -R ${DEFAULT_JAIL_ETC_SOURCE} ${CELL}/etc" && \
    run "${SED_BIN} -i '' -e \"s:__JAIL_NAME:${JAIL_NAME}.home:\" ${CELL}/etc/rc.conf" && \
    run "${SED_BIN} -i '' -e \"s:__HOST_IP:${JAIL_ROUTER_ADDRESS}:\" ${CELL}/etc/resolv.conf" && \
        note "Built initial jail environment"

    # run "${INSTALL_BIN} -v /etc/sofin.conf.sh ${CELL}/etc/" && \
    # run "${INSTALL_BIN} -v /usr/bin/sofin-version-utility ${CELL}/usr/bin" && \
    # run "${INSTALL_BIN} -v /usr/bin/sofin-microseconds ${CELL}/usr/bin" && \
        # note "Instaled local Sofin to: ${cyan}${CELL}"

    if [ ! -f "${CELL}/etc/sysctl.conf" ]; then
        run "${CP_BIN} -v ${SERVED_REPO}/etc-jail/sysctl.conf ${CELL}/etc/sysctl.conf" && \
        note "Created sysctl.conf from svdOS repository"
    fi

    run "${RM_BIN} -f ${CELL}/etc/zshenv ${CELL}/etc/zshrc" && \
    run "${MKDIR_BIN} -p ${CELL}/etc/zsh" && \
    run "${CP_BIN} -R ${SERVED_REPO}/shell/ ${CELL}/etc/zsh" && \
    run "${MV_BIN} -v ${CELL}/etc/zsh/zshrc ${CELL}/etc/zshrc" && \
    run "${MV_BIN} -v ${CELL}/etc/zsh/zshenv ${CELL}/etc/zshenv" && \
        note "Jail system shell configured"

    # run "${MV_BIN} ${CELL}/usr/bin/make ${CELL}/usr/bin/bsdmake" && \
    # run "${CP_BIN} ${GMAKE_BIN} ${CELL}/usr/bin/make" && \
    #     note "Replaced default BSD make with GNU make (which is expected when Gold LD is installed)"

    svd_version="$(${ZFS_BIN} get -H -o value com.svd:version ${DEFAULT_ZPOOL}/ROOT 2>/dev/null)"
    run "${ZFS_BIN} set com.svd:version=${svd_version} ${DEFAULT_ZPOOL}${CELL}" && \
        note "Updated client ServeD version property from base system"

    for logger in messages production staging development; do
        run "${MKFIFO_BIN} -m \"a=-rwx,u=rw\" \"${CELL}/var/log/${logger}\"" && \
        ${CHOWN_BIN} "${EPAIR_NUMBER}" "${CELL}/var/log/${logger}" && \
        printf "
source s_${JAIL_NAME}_${logger} {
    pipe(\"${CELL}/var/log/${logger}\");
};
destination d_${JAIL_NAME}_${logger}_file {
    file(\"/var/log/${JAIL_NAME}-${logger}.log\" template(t_default_format));
};
log {
    source(s_${JAIL_NAME}_${logger});
    destination(d_${JAIL_NAME}_${logger}_file);
};
" > "${JAIL_LOGS_CONF_DIR}/${logger}.conf" && \
        note "Created logger: ${logger}"
    done

    note "Reloading syslog"
    service syslog-ng reload >/dev/null || service syslog-ng restart >/dev/null

    note "Setting up home domains from main IPs: ${JAIL_ADDRESSES}"
    MAIN_JAIL_ADDRESS="$(echo "${JAIL_ADDRESSES}" | ${SED_BIN} -e 's#/.*# #g' 2>/dev/null)"

    printf "
# Default home zone template:
local-zone: \"${JAIL_NAME}.home.\" redirect

local-data: \"${JAIL_NAME}.home. 10800 IN NS ns1.${JAIL_NAME}.home.\"
local-data: \"${JAIL_NAME}.home. 10800 IN NS ns2.${JAIL_NAME}.home.\"
local-data: \"${JAIL_NAME}.home. 1800  IN SRV 10 10 22 ${JAIL_NAME}.home.\"
local-data: \"${JAIL_NAME}.home. 10800 IN SOA ns1.${JAIL_NAME}.home. ns2.${JAIL_NAME}.home. $(${DATE_BIN} +%s 2>/dev/null) 3600 600 86400 3600\"
local-data: \"${JAIL_NAME}.home. 10800 IN A ${MAIN_JAIL_ADDRESS}\"

local-data-ptr: \"${MAIN_JAIL_ADDRESS} ${JAIL_NAME}.home\"

" >> "${JAIL_LOCAL_DOMAIN_CONF}"

    run "service local_unbound configtest" && \
    run "service local_unbound restart" && \
    jail_start "${JAIL_NAME}" && \
        note "Zone: ${cyan}${JAIL_NAME}.home ${green}is now locally resolvable. Owned by: ${cyan}${JAIL_NAME}" && \
        return 0

    error "Failed to successfully reload zone: ${cyan}${JAIL_NAME}.home"
}


jail_status () {
    usage () {
        note "Usage: ${cyan}${GVR_SCRIPT_NAME} status jail-name${reset}"
    }
    GIVEN_NAME="${1}"
    VERBOSE="${2}"
    if [ -z "${GIVEN_NAME}" ]; then
        usage
        error "No jail name given"
    fi
    set_values "${GIVEN_NAME}"
    check_cell_name "${CELL}"

    printf "Status: ${JAIL_STATUS}\n"
    echo "${JAIL_STATUS}" | ${GREP_BIN} '\*on\*' > /dev/null 2>&1
    if [ "$?" = "0" ]; then
        JAIL_NUM_ID="$(${JLS_BIN} -v 2>/dev/null | ${EGREP_BIN} "${JAIL_NAME}.home" 2>/dev/null | ${AWK_BIN} '{print $1;}' 2>/dev/null)"
        debug "JAIL_NUM_ID: ${JAIL_NUM_ID}"
        printf "JID: ${green}${JAIL_NUM_ID}${reset}\n"
    fi
    printf "Name: ${green}${JAIL_NAME}${reset}\n"
    printf "IPv4s: ${green}${JAIL_IPS}${reset}\n"
    printf "Interface: ${green}${EPAIR}${reset}\n"
    printf "Hostnames: ${green}${HOSTNAMES}${reset}\n"
    printf "OS version: ${green}${JAIL_VERSION}${reset}\n\n"
    if [ -d "${JAIL_ATTRIBUTES_DIR}" ]; then
        printf "Overriden attributes:\n"
        for attr in $(${FIND_BIN} "${JAIL_ATTRIBUTES_DIR}" -type f 2>/dev/null); do
            printf "${cyan}${attr##*/}: $(${CAT_BIN} "${attr}" 2>/dev/null)${reset}\n"
        done
        printf "\n"
    fi
    printf "Live attributes:\n${cyan}$(${RCTL_BIN} -h "jail:${JAIL_NAME}" 2>/dev/null | ${SED_BIN} 's/jail:n1://g' 2>/dev/null | ${SED_BIN} 's/:deny=/: /g' 2>/dev/null)${reset}\n"
    case ${VERBOSE} in
        v|-v|-verbose|verbose|more)
            printf "\nFull configuration:"
            printf "${cyan}$(${CAT_BIN} "${JAIL_CONF_FILE}" 2>/dev/null)\n"
            ;;
    esac
}


jail_list () {
    cd ${DEFAULT_CELLS_LOCATION}
    for cell in $(${LS_BIN} 2>/dev/null); do
        cellname="$(printf "${cell}" | ${AWK_BIN} '{print substr($1,0,29);}' 2>/dev/null)" # first 29 chars visible in jls output
        printf "${cell}"
        if [ -f "${DEFAULT_SENTRY_LOCATION}/${cellname}/${CELL_IP_ADDRESSES_ATTRIBUTE}" ]; then
            JAIL_IPS="$(${CAT_BIN} "${DEFAULT_SENTRY_LOCATION}/${cellname}/${CELL_IP_ADDRESSES_ATTRIBUTE}" 2>/dev/null | ${TR_BIN} '\n' ',' 2>/dev/null | ${SED_BIN} -e 's/,$//' 2>/dev/null)"
        fi
        ${JLS_BIN} -v | ${EGREP_BIN} "${cellname} .*ACTIVE" >> ${GVR_LOG} 2>&1
        if [ "$?" = "0" ]; then
            printf " ${cyan}${JAIL_IPS}${reset} ${green}*on*${reset}"
        else
            printf " ${cyan}${JAIL_IPS}${reset} ${red}*off*${reset}"
        fi
        printf "\n"
    done
}


# Apply settings and start jail
jail_start () {
    usage () {
        note "Usage: ${cyan}${GVR_SCRIPT_NAME} start jail-name"
    }
    GIVEN_NAME="${1}" # hostname?
    if [ -z "${GIVEN_NAME}" ]; then
        usage
        error "No jail to start"
    fi
    set_values "${GIVEN_NAME}"

    ${JLS_BIN} -v 2>/dev/null | ${EGREP_BIN} "${GIVEN_NAME}.home" > /dev/null 2>&1
    if [ "$?" = "0" ]; then
        note "Jail with name: ${cyan}${GIVEN_NAME}${green} is already running"
        exit 0
    fi

    check_cell_name "${CELL}"
    if [ -f "${JAIL_ADDRESSES_FILE}" ]; then
        JAIL_IPS="$(${CAT_BIN} "${JAIL_ADDRESSES_FILE}" 2>/dev/null | ${TR_BIN} ',' '\n' 2>/dev/null)"
    fi

    # run "${IFCONFIG_BIN} ${EPAIR} || (${IFCONFIG_BIN} ${EPAIR} create && ${IFCONFIG_BIN} ${EPAIR} ${EPAIR_DEVICE} ${EPAIR_NUMBER} vlandev ${DEFAULT_INTERFACE})" && \
    #     note "Configured virtual lan device: ${cyan}${EPAIR}"

    # run "${IFCONFIG_BIN} ${BRIDGE_DEVICE} || (${IFCONFIG_BIN} ${BRIDGE_DEVICE} create && ${IFCONFIG_BIN} ${BRIDGE_DEVICE} addm ${DEFAULT_INTERFACE} stp ${DEFAULT_INTERFACE} sticky ${DEFAULT_INTERFACE} && ${IFCONFIG_BIN} ${BRIDGE_DEVICE} addm ${EPAIR} sticky ${EPAIR})" && \
        # note "Successfully attached virtual device: ${cyan}${EPAIR}${green}, to local bridge: ${cyan}${BRIDGE_DEVICE}"
    # for ip in ${JAIL_IPS}; do
    #     run "${IFCONFIG_BIN} ${EPAIR} ${ip} alias" && \
    #         note "Attached network alias for: ${cyan}${ip}${green}, to: ${cyan}${EPAIR}"
    # done

    ${DEBUG_COMMAND} "${JAIL_BIN}" -c -J "${JAIL_ID_FILE}" -f "${JAIL_CONF_FILE}" >> "${GVR_LOG}" 2>> "${GVR_LOG}"
    if [ "$?" = "0" ]; then
        JAIL_NUM_ID="$(${JLS_BIN} 2>/dev/null | ${EGREP_BIN} "${JAIL_NAME}" 2>/dev/null | ${AWK_BIN} '{print $1;}' 2>/dev/null)"
        permnote "Deployed jail: ${cyan}${JAIL_NAME} ${green}(JID: ${JAIL_NUM_ID})"

        printf "[launched by ${USER} on $(${DATE_BIN} +%F-%H%M%S 2>/dev/null)]" > "${JAIL_STATUS_FILE}"
        # note "Launching Service Spawner daemon"
        # ${JEXEC_BIN} -U ${DEFAULT_JAIL_USER} ${JAIL_NAME} ${IGNITER_INSTALL_BIN} >> ${GVR_LOG} 2>&1
        # ${JEXEC_BIN} -U ${DEFAULT_JAIL_USER} ${JAIL_NAME} daemon ${SERVICE_SPAWNER_BIN}
        ${JEXEC_BIN} -U root "${JAIL_NAME}" "${PW_BIN}" usermod "${DEFAULT_JAIL_USER}" -u "${EPAIR_NUMBER}" && \
            permnote "Jailed worker user ID: ${cyan}${EPAIR_NUMBER}"

        # alow users creating / in their tree. why not.
        run "${JEXEC_BIN} -U root ${JAIL_NAME} ${CHMOD_BIN} 771 /" && \
        run "${JEXEC_BIN} -U root ${JAIL_NAME} ${CHMOD_BIN} 777 /tmp" && \
            debug "Permissions of jailed / set to 771, /tmp to 777"
        # ${JEXEC_BIN} -U root ${JAIL_NAME} secadm -c /etc/secadm.rules set >> ${GVR_LOG} 2>&1

        # ${JEXEC_BIN} -U root ${JAIL_NAME} ${IGNITER_INSTALL_BIN} >> ${GVR_LOG} 2>&1
        # ${JEXEC_BIN} -U root ${JAIL_NAME} daemon ${SERVICE_SPAWNER_BIN}
        apply_attributes

        if [ -z "${JAIL_NUM_ID}" ]; then
            error "Jail ID is empty!"
        fi
        for dset in Services Software Shared User; do
            run "${ZFS_BIN} jail ${JAIL_NUM_ID} ${DEFAULT_ZPOOL}/${dset}/${JAIL_NAME}" && \
            run "${ZFS_BIN} set canmount=on ${DEFAULT_ZPOOL}/${dset}/${JAIL_NAME}" && \
            run "${ZFS_BIN} set jailed=on ${DEFAULT_ZPOOL}/${dset}/${JAIL_NAME}" && \
                permnote "Filesystem jailed: ${cyan}${dset}"
        done

        run "${JEXEC_BIN} -U root ${JAIL_NAME} ${CHMOD_BIN} +s ${SYSCTL_BIN} ${ZFS_BIN} ${CHOWN_BIN}" && \
        run "${JEXEC_BIN} -U root ${JAIL_NAME} ${CHOWN_BIN} ${EPAIR_NUMBER} /Services /User /Software /Shared /SystemUsers"
        run "${JEXEC_BIN} -U ${DEFAULT_JAIL_USER} ${JAIL_NAME} ${ZFS_BIN} mount -a" && \
            permnote "Zfs datasets mounted"
        run "${JEXEC_BIN} -U root ${JAIL_NAME} mount -a"
        run "${JEXEC_BIN} -U root ${JAIL_NAME} ${SYSCTL_BIN} kern.securelevel=${KERN_SECURELEVEL}" && \
            note "Securelevel set to: ${cyan}${KERN_SECURELEVEL}"
        run "${JEXEC_BIN} -U ${DEFAULT_JAIL_USER} ${JAIL_NAME} ${DEFAULT_SHELL} -c '${SOFIN_BIN} reload'" && \
            note "Reloaded shell environment. Marking jail running" && \
            mark_running
    else
        ${IFCONFIG_BIN} "${EPAIR}b" destroy 2>/dev/null
        error "Jail launch failed. Look into log file: ${cyan}${GVR_LOG}"
    fi
}


jail_stop () {
    usage () {
        note "Usage: ${cyan}${GVR_SCRIPT_NAME} stop jail-name${reset}"
    }
    GIVEN_NAME="${1}"
    if [ -z "${GIVEN_NAME}" ]; then
        usage
        error "No jail to stop"
    fi
    set_values "${GIVEN_NAME}"
    check_cell_name "${CELL}"
    JAIL_NUM_ID="$(${JLS_BIN} -v 2>/dev/null | ${EGREP_BIN} "${JAIL_NAME}.home" 2>/dev/null | ${AWK_BIN} '{print $1;}' 2>/dev/null)"
    for dir in /dev; do
        ${MOUNT_BIN} >/dev/null 2>&1 | ${GREP_BIN} "${CELL}${dir}" >/dev/null 2>&1 && \
        run "${UMOUNT_BIN} -f ${CELL}${dir}" && \
            note "Unmounted: ${cyan}${dir}"
    done
    for dset in User Services Software; do
        if [ ! -z "${JAIL_NUM_ID}" ]; then
            run "${ZFS_BIN} unjail ${JAIL_NUM_ID} ${DEFAULT_ZPOOL}/${dset}/${JAIL_NAME}"
        fi
        # run "${ZFS_BIN} umount -f ${DEFAULT_ZPOOL}/${dset}/${JAIL_NAME}" || \
        run "${ZFS_BIN} set canmount=off ${DEFAULT_ZPOOL}/${dset}/${JAIL_NAME}" || \
            note "Unjailed and unmounted: ${cyan}${dset}"
    done

    run "${DEBUG_EXEC_COMMAND} ${JAIL_BIN} -r ${JAIL_NAME}" && \
        note "Terminated jail: ${cyan}${JAIL_NAME}"

    printf "[terminated by ${USER} on $(${DATE_BIN} +%F-%H-%M-%S)]" > "${JAIL_STATUS_FILE}"

    run "${RM_BIN} -f ${SENTRY}/${JAIL_RUNNING_INDICATOR}" && \
        note "Removed jail running indicator: ${cyan}${SENTRY}/${JAIL_RUNNING_INDICATOR}"
}


jail_set () {
    usage () {
        note "Usage: ${cyan}${GVR_SCRIPT_NAME} set jail-name attribute=value attr2=val2 (...)"
    }
    GIVEN_NAME="${1}"
    shift
    if [ -z "${GIVEN_NAME}" ]; then
        usage
        error "No jail name given"
    fi

    set_values "${GIVEN_NAME}"
    check_cell_name "${CELL}"
    for argument_pair in ${*}; do
        ATTRIBUTE="$(printf "${argument_pair}\n" | ${AWK_BIN} '{split($0, a, "="); print a[1];}' 2>/dev/null)"
        JAIL_VALUE="$(printf "${argument_pair}\n" | ${AWK_BIN} '{split($0, a, "="); print a[2];}' 2>/dev/null)"
        debug "arg: ${ATTRIBUTE}, val: ${JAIL_VALUE} "
        note "Setting attribute: ${cyan}${ATTRIBUTE}${green}, value: ${cyan}${JAIL_VALUE}${green} for jail: ${cyan}${JAIL_NAME}"
        printf "${JAIL_VALUE}\n" > "${JAIL_ATTRIBUTES_DIR}/${ATTRIBUTE}"
    done
    apply_attributes
}


jail_unset () {
    usage () {
        note "Usage: ${cyan}${GVR_SCRIPT_NAME} unset jail-name attribute value"
    }
    GIVEN_NAME="${1}"
    if [ -z "${GIVEN_NAME}" ]; then
        usage
        error "No jail name given"
    fi
    shift

    set_values "${GIVEN_NAME}"
    check_cell_name "${CELL}"
    for jail_attribute in ${*}; do
        run "${RM_BIN} -f ${JAIL_ATTRIBUTES_DIR}/${jail_attribute}" && \
        run "${RCTL_BIN} -r jail:${JAIL_NAME}:${jail_attribute}" && \
            note "Unset attribute: ${cyan}${jail_attribute}${green} for jail: ${cyan}${JAIL_NAME}"
    done
    apply_attributes
}


jail_login () {
    usage () {
        note "Usage: ${cyan}${GVR_SCRIPT_NAME} login jail-name"
    }
    GIVEN_NAME="${1}" # hostname?
    if [ -z "${GIVEN_NAME}" ]; then
        usage
        error "No jail to enter"
    fi
    JAIL_LOGIN="${DEFAULT_JAIL_USER}"
    GIVEN_USER="${2}"
    if [ "${GIVEN_USER}" != "" ]; then
        JAIL_LOGIN="${GIVEN_USER}"
    fi
    set_values "${GIVEN_NAME}"
    check_cell_name "${CELL}"
    ${JLS_BIN} -v 2>/dev/null | ${GREP_BIN} "$(${BASENAME_BIN} "${CELL}" 2>/dev/null) .*ACTIVE" >> ${GVR_LOG} 2>> ${GVR_LOG}
    if [ "$?" = "0" ]; then
        debug "Logging in as: ${JAIL_LOGIN} to jail: ${JAIL_NAME}" && \
        ${DEBUG_EXEC_COMMAND} "${JEXEC_BIN}" "${JAIL_NAME}" login -f "${JAIL_LOGIN}" && \
            note "Logged out from jail: ${cyan}${JAIL_NAME}"
    else
        error "Start jail first!"
    fi
}


jail_restart () {
    usage () {
        note "Usage: ${cyan}${GVR_SCRIPT_NAME} restart jail-name${reset}"
    }
    GIVEN_NAME="${1}"
    if [ -z "${GIVEN_NAME}" ]; then
        usage
        error "No jail to restart"
    fi
    jail_stop ${*}
    jail_start ${*}
}


jail_destroy () {
    usage () {
        note "Usage: ${cyan}${GVR_SCRIPT_NAME} destroy jail-name${reset}"
    }
    GIVEN_NAME="${1}"
    if [ -z "${GIVEN_NAME}" ]; then
        usage
        error "No jail to destroy"
    fi
    set_values "${GIVEN_NAME}"
    check_cell_name "${CELL}"

    note "Are you sure you want to destroy jail: ${cyan}$(${BASENAME_BIN} "${GIVEN_NAME}")${green} with ${red}ALL SERVICES DATA?"
    note "Type ${cyan}YES${green} to confirm"
    read -r ans
    if [ "${ans}" = "YES" ]; then
        if [ -f "${SENTRY}/${JAIL_RUNNING_INDICATOR}" ]; then
            jail_stop ${*}
        fi
        run "${ZFS_BIN} destroy -rf ${DEFAULT_ZPOOL}/Software/${JAIL_NAME}" && \
        run "${ZFS_BIN} destroy -rf ${DEFAULT_ZPOOL}/Services/${JAIL_NAME}" && \
        run "${ZFS_BIN} destroy -rf ${DEFAULT_ZPOOL}/Shared/${JAIL_NAME}" && \
        run "${ZFS_BIN} destroy -rf ${DEFAULT_ZPOOL}/User/${JAIL_NAME}" && \
        run "${ZFS_BIN} destroy -rf ${DEFAULT_ZPOOL}${SENTRY}" && \
        run "${ZFS_BIN} destroy -rf ${DEFAULT_ZPOOL}${CELL}" && \
        run "${RM_BIN} -rf ${CELL}" && \
        run "${RM_BIN} -rf ${SENTRY}" && \
            note "Destroyed datasets of jail: ${cyan}${JAIL_NAME}" && \
            service local_unbound configtest >> ${GVR_LOG} 2>&1 && \
            service local_unbound restart >> ${GVR_LOG} 2>&1 && \
                note "Unbound resolver restarted"
    else
        note "Jail: ${cyan}$(${BASENAME_BIN} "${GIVEN_NAME}" 2>/dev/null) left intact"
    fi
}


case $1 in
    ver|v|version)
        shift
        show_version
        ;;

    create|c)
        shift
        jail_create ${*}
        ;;

    destroy)
        shift
        jail_destroy ${*}
        ;;

    status|s|stat)
        shift
        jail_status ${*}
        ;;

    start)
        shift
        jail_start ${*}
        ;;

    stop)
        shift
        jail_stop ${*}
        ;;

    restart)
        shift
        jail_restart ${*}
        ;;

    list|l|lst)
        shift
        jail_list ${*}
        ;;

    set)
        shift
        jail_set ${*}
        ;;

    unset)
        shift
        jail_unset ${*}
        ;;

    login)
        shift
        jail_login ${*}
        ;;

    attributes|attrs)
        attributes_show
        ;;

    boot)
        cd ${DEFAULT_SENTRY_LOCATION}
        for jail in *; do
            if [ -f "${DEFAULT_SENTRY_LOCATION}/${jail}/${JAIL_RUNNING_INDICATOR}" ]; then
                note "Initializing boot of jail: ${cyan}${jail}"
                nohup "${0}" start "${jail}" > /dev/null 2>&1 &
            else
                warn "Boot skipped: ${cyan}${jail}"
            fi
        done
        ;;

    *)
        CMD="${GVR_SCRIPT_NAME}"
        note "Usage:"
        note "  ${CMD} command arg1 arg2 [...]"
        note
        note "List of commands:"
        note "  ${cyan}ver${reset}: ${green}prints Governor and svdOS versions${reset}"
        note "  ${cyan}boot${reset}: ${green}launches all previously running jails${reset}"
        note "  ${cyan}create${reset}: ${green}creates new jail${reset}"
        note "  ${cyan}list${reset} | ${cyan}lst${reset} | ${cyan}l${reset}: ${green}lists created jails${reset}"
        note "  ${cyan}set${reset}: ${green}set attributes for jails${reset}"
        note "  ${cyan}attributes${reset} | ${cyan}attrs${reset}: ${green}shows attributes list modifiable by '${CMD} set …' ${reset}"
        note "  ${cyan}login${reset}: ${green}logins to jail${reset}"
        note "  ${cyan}start${reset}: ${green}starts created, non running jail${reset}"
        note "  ${cyan}stop${reset}: ${green}stops running jail${reset}"
        note "  ${cyan}restart${reset}: ${green}restarts a jail${reset}"
        note "  ${cyan}status${reset}: ${green}shows detailed configuration of a jail${reset}"
        note "  ${cyan}destroy${reset}: ${green}destroys a jail${reset}"
        note
        note "Run '${CMD} [command]' without arguments to see detailed help about command params."
        ;;
esac


exit 0
