#!/bin/sh

setup_buildhost () {
    if [ "${SYSTEM_NAME}" = "FreeBSD" ]; then
        ${UNAME_BIN} -a | ${GREP_BIN} "HBSD" >/dev/null 2>&1
        if [ "$?" = "0" ]; then
            note "Setting some zfs options"
            zfs set primarycache=metadata ${DEFAULT_ZPOOL}
            zfs set secondarycache=metadata ${DEFAULT_ZPOOL}
            sysctl vfs.zfs.prefetch_disable=1
            sysctl debug.witness.trace=0
            sysctl debug.witness.watch=0

            note "Setting pageexec and mprotect to 1 for build purposes"
            sysctl hardening.pax.pageexec.status=1
            sysctl hardening.pax.mprotect.status=1

            set +e
            note "Loading Dtrace"
            kldload dtraceall

            note "Creating ~/.ssh/config"
            echo "Host verknowsys.com *.verknowsys.com" > ~/.ssh/config
            echo "Port 60022" >> ~/.ssh/config

            note "Turning off Syslog-ng (is part of /Software so cannot be run on build host)"
            sed -i '' -e 's#syslog_ng_enable="YES"#syslog_ng_enable="NO"#' /etc/rc.conf 2>/dev/null
            killall -9 syslog-ng >/dev/null 2>&1

            zfs destroy ${DEFAULT_ZPOOL}/usr/src 2>/dev/null
            zfs destroy ${DEFAULT_ZPOOL}/usr/obj 2>/dev/null

            note "Setting up and mounting ramdisks"
            mkdir -p /usr/src /usr/obj ~/.cache/cache
            mount | grep '.cache/cache' > /dev/null 2>&1
            if [ "$?" != "0" ]; then
                mdmfs -s4G md ~/.cache/cache
            fi
            mount | grep '/usr/src' > /dev/null 2>&1
            if [ "$?" != "0" ]; then
                mdmfs -s5G md /usr/src
            fi
            mount | grep '/usr/obj' > /dev/null 2>&1
            if [ "$?" != "0" ]; then
                mdmfs -s4G md /usr/obj
            fi
            set -e

            echo "ServeD-BH" > /.build-host
        fi
    else
        error "System not supported."
    fi
}
