#!/bin/sh

readonly CONF_FILE="/etc/sofin.conf.sh"
if [ -e "${CONF_FILE}" ]; then
    . "${CONF_FILE}"
    validate_env
else
    echo "FATAL: No configuration file found: ${CONF_FILE}. Sofin isn't installed properly."
    exit 1
fi


if [ "${SYSTEM_NAME}" = "FreeBSD" ]; then
    ${UNAME_BIN} -a | ${GREP_BIN} "HBSD" >/dev/null 2>&1
    if [ "$?" = "0" ]; then
        note "Setting pageexec and mprotect to 1 for build purposes"
        sysctl hardening.pax.pageexec.status=1
        sysctl hardening.pax.mprotect.status=1

        note "Loading Dtrace"
        kldload dtraceall

        note "Creating ~/.ssh/config"
        echo "Host verknowsys.com *.verknowsys.com" > ~/.ssh/config
        echo "Port 60022" >> ~/.ssh/config

        note "Turning off Syslog-ng (is part of /Software so cannot be run on build host)"
        sed -i '' -e 's#syslog_ng_enable="YES"#syslog_ng_enable="NO"#' /etc/rc.conf 2>/dev/null
        killall -9 syslog-ng >/dev/null 2>&1

        note "Purging Sofin cache"
        s purge

        note "Setting up ramdisks"
        mkdir -p /usr/src /usr/obj ~/.cache/cache
        umount -f /usr/src
        umount -f /usr/obj
        umount -f /User/.cache/cache

        grep '.cache/cache' /etc/fstab > /dev/null 2>&1
        if [ "$?" != "0" ]; then
            printf "md     /User/.cache/cache    mfs   rw,-s4G 0 0\n" >> /etc/fstab
        fi
        grep '/usr/src' /etc/fstab > /dev/null 2>&1
        if [ "$?" != "0" ]; then
            printf "md     /usr/src    mfs   rw,-s5G 0 0\n" >> /etc/fstab
        fi
        grep '/usr/obj' /etc/fstab > /dev/null 2>&1
        if [ "$?" != "0" ]; then
            printf "md     /usr/obj    mfs   rw,-s4G 0 0\n" >> /etc/fstab
        fi

        note "Mounting ramdisks"
        mount /usr/obj
        mount /usr/src
        mount /User/.cache/cache
    fi
else

fi
