#!/bin/sh


# Literals:
CACHE_DIR="/var/.cache"
SOFTWARE_DIR="/Software"
SERVICES_DIR="/Services"
SHARED_DIR="/Shared"
SOURCE="http://software.verknowsys.com/binary/ServeD"
PATH="/Software/Git/exports:/Software/Zsh/exports:/bin:/usr/bin:/sbin:/usr/sbin"
HOME_DIR="/User"
SOFIN_BIN_REPO="http://software.verknowsys.com/binary"
ORIGINS_REPO="https://github.com/VerKnowSys/svdOS/raw/master/Origins/11"
ZFSX_EXT=".zfsx"
ZFSP_EXT=".zfsp"
ORIGIN="origin"
PROD_OS_BASE="FreeBSD-11.0-amd64"
GIT_VERSION="2.12.3"
ZSH_VERSION="5.3.1"
DATE_NOW="$(date +%F 2>/dev/null)"
LOG_FILE="/var/log/svdUP-${DATE_NOW:-common}.log"


get_the_current () {
    mkdir -p "${CACHE_DIR}" "${DESTBASE}" >/dev/null 2>&1
    fetch "${SOURCE}/current" -o "${CACHE_DIR}/current" \
        >> "${LOG_FILE}" 2>> "${LOG_FILE}" && \
        cat "${CACHE_DIR}/current" 2>/dev/null && \
        return 0
    return 1
}


prepare_and_fetch_os_snapshot () {
    test -f /etc/ssl/cert.pem || \
        fetch --no-verify-peer http://software.verknowsys.com/source/cacert.pem -o /etc/ssl/cert.pem

    test -f "${CACHE_DIR}/${MOST_RECENT}" || \
        fetch "${SOURCE}/${MOST_RECENT}" -o "${CACHE_DIR}/${MOST_RECENT}" \
            >> "${LOG_FILE}" && return 0
    return 1
}


determine_boot_disk_device () {
    for _dsk in $(geom disk list 2>/dev/null | egrep -i "Geom name:" 2>/dev/null | sed 's/^.*\: //' 2>/dev/null); do
        zpool status "${ZPOOL}" 2>/dev/null | \
            egrep -i "${_dsk}p[0-9]+" >/dev/null 2>&1 && \
            printf '%s\n' "${_dsk}" && \
            return 0
    done

    return 1
}


install_boot_environment () {
    zfs list "${ZPOOL}/ROOT/${NEW_BOOT_ENV}" >/dev/null 2>&1
    if [ "0" = "${?}" ]; then
        echo "svdUP: Boot environment: ${NEW_BOOT_ENV} is already received! Redundant operation cancelled!"
        return 6
    else
        xzcat "${CACHE_DIR}/${MOST_RECENT}" 2>/dev/null | zfs receive -u "${ZPOOL}/ROOT/${NEW_BOOT_ENV}" && \
            echo "svdUP: Snapshot file: ${MOST_RECENT%%.zfsx} was received as new boot environment: ${ZPOOL}/ROOT/${NEW_BOOT_ENV}!" && \
            return 0
        return 1
    fi
}


set_std_zfs_properties () {
    zfs set sync=standard "${ZPOOL}/ROOT/${NEW_BOOT_ENV}"
    zfs set checksum=fletcher4 "${ZPOOL}/ROOT/${NEW_BOOT_ENV}"
    zfs set readonly=off "${ZPOOL}/ROOT/${NEW_BOOT_ENV}"
    echo "svdUP: Production params were set for ROOT dataset: ${ZPOOL}/ROOT/${NEW_BOOT_ENV}"
    return 0
}


mount_boot_env () {
    beadm mount "${NEW_BOOT_ENV}" "${DESTBASE}" && \
        echo "svdUP: Mounted new environment: ${NEW_BOOT_ENV}, to destination base: ${DESTBASE}" && \
        return 0
    return 1
}


configure_and_commit_boot_env () {
    _boot_device="${1}"

    mount_boot_env && \
        test -f "${DESTBASE}/boot/pmbr" || exit 177

    echo "svdUP: Synchronising system configurations"
    cp -fv "/boot/loader.conf" "${DESTBASE}/boot/"
    cp -fv "/etc/hostid" "${DESTBASE}/etc/"
    cp -fv "/etc/rc.conf" "${DESTBASE}/etc/"
    cp -fv "/etc/rc.conf.local" "${DESTBASE}/etc/"
    cp -fv "/etc/pf.conf" "${DESTBASE}/etc/"
    cp -fv /etc/*pwd.db "${DESTBASE}/etc/"
    cp -fv "/etc/hosts" "${DESTBASE}/etc/"
    cp -fv "/etc/crontab" "${DESTBASE}/etc/"
    cp -fv "/etc/passwd" "${DESTBASE}/etc/"
    cp -fv "/etc/group" "${DESTBASE}/etc/"
    cp -fv "/etc/login.conf" "${DESTBASE}/etc/"
    cp -fv "/etc/sysctl.conf" "${DESTBASE}/etc/"
    cp -fv "/etc/shells" "${DESTBASE}/etc/"
    cp -fv "/etc/ttys" "${DESTBASE}/etc/"
    cp -fv "/etc/master.passwd" "${DESTBASE}/etc/"
    cp -fv "/etc/ssh/ssh_config" "${DESTBASE}/etc/ssh/"
    cp -fv "/etc/ssh/sshd_config" "${DESTBASE}/etc/ssh/"
    cp -fv /etc/ssh/ssh_host_* "${DESTBASE}/etc/ssh/"
    mv -fv "${DESTBASE}/etc/fstab" "${DESTBASE}/etc/_fstab"
    touch "${DESTBASE}/etc/fstab"

    gpart bootcode \
        -b "${DESTBASE}/boot/pmbr" \
        -p "${DESTBASE}/boot/gptzfsboot" \
        -i 1 \
        "${_boot_device}" && \
        echo "svdUP: Gpart: Bootcode: Environment: ${NEW_BOOT_ENV}, boot device: ${_boot_device}"

    beadm umount -f "${NEW_BOOT_ENV}" && \
        echo "svdUP: Unmounted new environment: ${NEW_BOOT_ENV}" && \
            return 0

    return 1
}


activate_new_boot_env () {
    beadm activate "${NEW_BOOT_ENV}" && \
        echo "svdUP: Commited and activated new boot environment: ${NEW_BOOT_ENV}" && \
        return 0
    return 1
}


install_svd_goodies () {
    echo "svdUP: Configuring datasets, installing base software, setting HOME to ${HOME_DIR}, Zsh as default shell"
    for _dataset_origin in User Services Software; do
        zfs list "${ZPOOL}/${_dataset_origin}" >/dev/null 2>&1
        if [ "${?}" != "0" ]; then
            zfs create \
                -o mountpoint=none \
                -o casesensitivity=sensitive \
                -o readonly=off \
                -o utf8only=on \
                -o dedup=off \
                -o checksum=fletcher4 \
                -o atime=off \
                -o aclmode=discard \
                -o exec=on \
                -o compression=lz4 \
                "${ZPOOL}/${_dataset_origin}" && \
                echo "svdUP: Created origin base: ${ZPOOL}/${_dataset_origin}"
        fi

        zfs list "${ZPOOL}/${_dataset_origin}/root" >/dev/null 2>&1
        if [ "${?}" != "0" ]; then
            # fetch origin!
            fetch -o \
                "${CACHE_DIR}/${_dataset_origin}-${ORIGIN}.zfsx" \
                "${ORIGINS_REPO}/${_dataset_origin}-${ORIGIN}.zfsx"
            xzcat "${CACHE_DIR}/${_dataset_origin}-${ORIGIN}.zfsx" | zfs receive -v "${ZPOOL}/${_dataset_origin}/root@${ORIGIN}"
            zfs set mountpoint="/${_dataset_origin}" "${ZPOOL}/${_dataset_origin}/root"

            case "${_dataset_origin}" in
                Services)
                    fetch -o "${CACHE_DIR}/Zsh-common${ZFSP_EXT}" "${SOFIN_BIN_REPO}/Common/Zsh-${ZSH_VERSION}${ZFSP_EXT}" && xzcat "${CACHE_DIR}/Zsh-common${ZFSP_EXT}" | zfs receive -v "${ZPOOL}${SERVICES_DIR}/root/Zsh"
                    fetch -o "${CACHE_DIR}/Git-common${ZFSP_EXT}" "${SOFIN_BIN_REPO}/Common/Git-${GIT_VERSION}${ZFSP_EXT}" && xzcat "${CACHE_DIR}/Git-common${ZFSP_EXT}" | zfs receive -v "${ZPOOL}${SERVICES_DIR}/root/Git"
                    ;;

                Software)
                    fetch -o "${CACHE_DIR}/Zsh-${ZSH_VERSION}${ZFSX_EXT}" "${SOFIN_BIN_REPO}/${PROD_OS_BASE}/Zsh-${ZSH_VERSION}-${PROD_OS_BASE}${ZFSX_EXT}"
                    zfs destroy -r "${ZPOOL}${SOFTWARE_DIR}/root/Zsh"
                    xzcat "${CACHE_DIR}/Zsh-${ZSH_VERSION}${ZFSX_EXT}" | zfs receive -v "${ZPOOL}${SOFTWARE_DIR}/root/Zsh"

                    fetch -o "${CACHE_DIR}/Git-${GIT_VERSION}${ZFSX_EXT}" "${SOFIN_BIN_REPO}/${PROD_OS_BASE}/Git-${GIT_VERSION}-${PROD_OS_BASE}${ZFSX_EXT}"
                    zfs destroy -r "${ZPOOL}${SOFTWARE_DIR}/root/Git"
                    xzcat "${CACHE_DIR}/Git-${GIT_VERSION}${ZFSX_EXT}" | zfs receive -v "${ZPOOL}${SOFTWARE_DIR}/root/Git"

                    egrep "/Software/Zsh/exports/zsh" /etc/shells || \
                        echo "/Software/Zsh/exports/zsh" >> /etc/shells
                    chsh -s /Software/Zsh/exports/zsh root
                    ;;

                User)
                    _new_home_mounted="$(zfs get -H -o value mounted "${ZPOOL}/${_new_home_mounted}/root" 2>/dev/null)"
                    if [ "yes" != "${_new_home_mounted}" ]; then
                        zfs mount "${ZPOOL}/${_dataset_origin}/root"
                        test -d "/root/.ssh" && cp -rf "/root/.ssh" "/${_dataset_origin}/"
                    fi
                    pw user mod root -d "/${_dataset_origin}"
                    pw user mod toor -d "/${_dataset_origin}"
                    ;;
            esac
        fi
    done
}


install_or_update_projects () {
    zfs list "${ZPOOL}/Projects" >/dev/null 2>&1
    if [ "${?}" != "0" ]; then
        zfs create \
            -o mountpoint=/Projects \
            -o casesensitivity=sensitive \
            -o readonly=off \
            -o utf8only=on \
            -o dedup=off \
            -o checksum=fletcher4 \
            -o atime=off \
            -o exec=on \
            -o compression=lz4 \
            "${ZPOOL}/Projects" && \
            echo "svdUP: Created origin base: ${ZPOOL}/Projects"
    fi

    test -f "${SERVICES_DIR}/Git/etc/ssl/cert.pem" || cp -f /etc/ssl/cert.pem "${SERVICES_DIR}/Git/etc/ssl/cert.pem"

    cd /Projects
    git clone https://github.com/VerKnowSys/sofin.git
    cd sofin
    git reset --hard
    bin/upgrade

    cd /Projects
    git clone https://github.com/vermaden/beadm.git
    cd beadm
    git reset --hard
    git pull origin master
    gzip beadm.1
    install -v beadm.1.gz /usr/share/man/man1/
    install -v beadm /usr/sbin/beadm

    cd /Projects
    git clone https://github.com/VerKnowSys/svdOS.git
    cd svdOS
    git reset --hard
    git pull origin master

    test -f /etc/rc.conf.local || cp -f etc/rc.production.conf /etc/rc.conf.local
    cp -fr shell/ /etc/zsh
    ln -fvs /etc/zsh/zshenv /etc/zshenv
    ln -fvs /etc/zsh/zshrc /etc/zshrc

    cd /
}


postinstall_cleanup () {
    zfs destroy -r "${ZPOOL}/var/mail"
    zfs set primarycache=all "${ZPOOL}/ROOT"
    zfs set secondarycache=all "${ZPOOL}/ROOT"
    zfs set checksum=fletcher4 "${ZPOOL}/ROOT"
    zfs set sync=standard "${ZPOOL}/ROOT"
    zfs set readonly=off "${ZPOOL}/ROOT"
    zfs set readonly=off "${ZPOOL}/ROOT/${NEW_BOOT_ENV}"

    rm -rf /.profile /.cshrc /mnt /media /proc /λ

    mkdir -p "${HOME_DIR}/.ssh"
    grep 'verknowsys.com' "${HOME_DIR}/.ssh/config" 2>/dev/null || \
        printf 'Host *.verknowsys.com verknowsys.com\nPort 60022\n\n' >> "${HOME_DIR}/.ssh/config"
}


#
# main():
#


# Most recent ServeD-OS snapshot:
MOST_RECENT="$(get_the_current)"
if [ -z "${MOST_RECENT}" ]; then
    echo "svdUP: svdUP: Fatal: Error: MOST_RECENT value is empty!"
    exit 5
fi

NEW_BOOT_ENV="${MOST_RECENT%%.zfsx}"
DESTBASE="${SHARED_DIR}/${NEW_BOOT_ENV}"
ZPOOL="${ZPOOL:-zroot}"

export PATH MOST_RECENT ZPOOL DESTBASE NEW_BOOT_ENV

# main():
BOOT_DEVICE="$(determine_boot_disk_device)"
if [ -z "${BOOT_DEVICE}" ]; then
    echo "svdUP: Fatal: Error: main(): Got empty boot device!"
    exit 6
fi
echo "svdUP: Default boot device: ${BOOT_DEVICE}"
echo "svdUP: Tasks in progress…" && \
    prepare_and_fetch_os_snapshot && \
    install_boot_environment && \
    set_std_zfs_properties && \
    install_svd_goodies && \
    install_or_update_projects && \
    configure_and_commit_boot_env "${BOOT_DEVICE}" && \
    postinstall_cleanup && \
    activate_new_boot_env && \
    echo "svdUP: All tasks were completed successfully!" && \
    exit 0

exit 1
