#!/bin/sh

set -e

. /Software/Sofin/share/loader

. ./setup-buildhost
. ./update-ports

setup_buildhost
s i Perl
export PATH=/Software/Perl/exports:/bin:/usr/bin:/sbin:/usr/sbin
update_ports

set +e
