#!/bin/sh
#
# blame: dmilith
# © 2011-2016 verknowsys.com
#
# PROVIDE: buildhost
# REQUIRE: NETWORK syslog-ng FILESYSTEMS mountcritremote
# KEYWORD: shutdown

. /etc/rc.subr


command="/usr/bin/true" # irrelevant

name="buildhost"
rcvar="buildhost_enable"
start_precmd="buildhost_prestart"
separator="---------------------------------------------------------------------------"

export SERVED_REPO="/var/ServeD-OS"
export PATH=/bin:/usr/bin:/sbin:/usr/sbin

buildhost_prestart () {
    if [ -f "/.build-host" ]; then
        echo "${separator}"
        printf "\nBuild-host: $(hostname -f)\n"
        . /usr/share/sofin/loader
        . ${SERVED_REPO}/setup-buildhost
        setup_buildhost
    fi
    printf "\nSystem is ready to serve!\n"
    echo "${separator}"
}

load_rc_config $name
run_rc_command "$1"
