#!/bin/sh
#
# $FreeBSD: head/etc/rc.d/casperd 259463 2013-12-16 11:03:59Z pjd $
#

# PROVIDE: casperd
# REQUIRE: NETWORKING syslogd
# BEFORE:  DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="casperd"
rcvar="casperd_enable"
pidfile="/var/run/${name}.pid"
command="/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
