#!/bin/sh
#
# blame: dmilith
# © 2011-2016 verknowsys.com
#
# PROVIDE: served
# REQUIRE: NETWORK syslog-ng FILESYSTEMS mountcritremote
# KEYWORD: shutdown

. /etc/rc.subr


command="/usr/bin/true" # irrelevant

name="served"
rcvar="served_enable"
start_precmd="served_prestart"
separator="---------------------------------------------------------------------------"

SERVED_REPO="/Projects/svdOS"
BUILD_HOST_MARKER="/.build-host"
PATH=/bin:/usr/bin:/sbin:/usr/sbin

served_prestart () {
    if [ -f "${BUILD_HOST_MARKER}" ]; then
        echo "${separator}"
        printf "\nBuild-host: $(hostname -f)\n"
        . /Software/Sofin/share/loader
        . ${SERVED_REPO}/setup-buildhost
        setup_buildhost
    fi
    printf "\nSystem is ready to serve!\n"
    echo "${separator}"
}

load_rc_config $name
run_rc_command "$1"
