#!/bin/sh

. /etc/sofin.conf.sh

JAIL_BIN="/usr/sbin/jail" # XXX: added in new sofin
JAIL_CONFIGURATION_FILE="/etc/jail.conf"
DEFAULT_CELLS_LOCATION="/Jails/Prison/Cells"
DEFAULT_SENTRY_LOCATION="/Jails/Prison/Sentry"
DEFAULT_JAIL_SHARED_LOCATION="/Jails/Shared"
DEFAULT_VERSION="10.1"
DEFAULT_INTERFACE="em0"
DEFAULT_ETC_ARCHIVE="etc-jail.tar.gz"

usage () {
    note "$0 jail-name.com IP-address fbsd-version net-interface"
    note "fbsd-version -> by default 10.1"
    note "net-interface -> by default em0"
}


note "Performing sanity checks"

if [ ! -f "${DEFAULT_ETC_ARCHIVE}" ]; then
    error "etc archive: ${DEFAULT_ETC_ARCHIVE} wasn't found. Cannot continue"
fi

JAIL_NAME="${1}" # hostname?
if [ "${1}" = "" ]; then
    note "No jail name given"
    usage
    exit 1
fi

JAIL_ADDRESS="${2}"
if [ "${2}" = "" ]; then
    note "No ip given"
    usage
    exit 1
fi

JAIL_VERSION="${3}"
if [ "${3}" = "" ]; then
    JAIL_VERSION="${DEFAULT_VERSION}"
fi

JAIL_INTERFACE="${4}"
if [ "${4}" = "" ]; then
    JAIL_INTERFACE="${DEFAULT_INTERFACE}"
fi

ping -c1 ${2} > /dev/null 2>&1
if [ "$?" != "0" ]; then
    error "Given IP address: ${2} must be available"
fi


CELL="${DEFAULT_CELLS_LOCATION}/${JAIL_NAME}"
SENTRY="${DEFAULT_SENTRY_LOCATION}/${JAIL_NAME}"
JAIL_ID_FILE="${SENTRY}/jail.id"
JAIL_SOURCE="${DEFAULT_JAIL_SHARED_LOCATION}/${SYSTEM_NAME}-${DEFAULT_VERSION}-${SYSTEM_ARCH}"

note "Creating dirs"
${MKDIR_BIN} -p "${CELL}"
${MKDIR_BIN} -p "${SENTRY}"

${GREP_BIN} "${JAIL_NAME}" ${JAIL_CONFIGURATION_FILE} > /dev/null 2>&1
if [ "$?" = "0" ]; then
    note "Jail configuration already in ${JAIL_CONFIGURATION_FILE}"
else
    note "Generating jail configuration"
    ${PRINTF_BIN} "
${JAIL_NAME} {
    name = \"${JAIL_NAME}\";
    host.hostname = \"${JAIL_NAME}\";
    ip4.addr = \"${JAIL_ADDRESS}\";
    interface = ${JAIL_INTERFACE};
    path = \"${CELL}\";
    exec.start = \"/bin/sh /etc/rc\";
    exec.stop = \"/bin/sh /etc/rc.shutdown\";
    enforce_statfs = 1;
    allow.mount = 1;
    allow.mount.nullfs = 1;
    allow.mount.zfs = 1;
    allow.mount.tmpfs = 1;
    allow.raw_sockets = 1;
    mount.devfs;
    persist;
}
" >> ${JAIL_CONFIGURATION_FILE}
fi


note "Copying jail directories"
if [ -d "${CELL}" ]; then
    error "Cell: ${CELL} already exists! Aborting"
fi
zfs create -o mountpoint=${CELL} zroot${CELL}
${CP_BIN} -R ${JAIL_SOURCE} ${CELL}

note "Making required jail directories"
${MKDIR_BIN} -p ${CELL}/tmp ${CELL}/dev

note "Installing default etc for jail"
${TAR_BIN} xf ${DEFAULT_ETC_ARCHIVE} --directory ${CELL}
${SED_BIN} -i "s:__JAIL_NAME:${JAIL_NAME}:" ${CELL}/etc/rc.conf

note "Launching jail: ${JAIL_NAME}"
${JAIL_BIN} -qcmr -J ${JAIL_ID_FILE}

