#!/bin/sh

. /etc/sofin.conf.sh

JAIL_BIN="/usr/sbin/jail" # XXX: added in new sofin
JAIL_CONFIGURATION_FILE="/etc/jail.conf"
DEFAULT_CELLS_LOCATION="/Jails/Prison/Cells"
DEFAULT_SENTRY_LOCATION="/Jails/Prison/Sentry"
DEFAULT_JAIL_SHARED_LOCATION="/Jails/Shared"
DEFAULT_VERSION="10.1"
DEFAULT_INTERFACE="em0"
DEFAULT_ETC_ARCHIVE="etc-jail.tar.xz"

usage () {
    note "$0 jail-name.com IP-address fbsd-version net-interface"
    note "fbsd-version -> by default 10.1"
    note "net-interface -> by default em0"
}


note "Performing sanity checks"

if [ ! -f "${DEFAULT_ETC_ARCHIVE}" ]; then
    error "etc archive: ${DEFAULT_ETC_ARCHIVE} wasn't found. Cannot continue"
fi

JAIL_HOSTNAME="${1}" # hostname?
if [ "${1}" = "" ]; then
    note "No jail hostname given"
    usage
    exit 1
fi
JAIL_NAME="$(${PRINTF_BIN} "${JAIL_HOSTNAME}\n" | ${SED_BIN} 's/\./-/g')"

JAIL_ADDRESS="${2}"
if [ "${2}" = "" ]; then
    note "No ip given"
    usage
    exit 1
fi

JAIL_VERSION="${3}"
if [ "${3}" = "" ]; then
    JAIL_VERSION="${DEFAULT_VERSION}"
fi

JAIL_INTERFACE="${4}"
if [ "${4}" = "" ]; then
    JAIL_INTERFACE="${DEFAULT_INTERFACE}"
fi

ping -c1 ${2} > /dev/null 2>&1
if [ "$?" != "0" ]; then
    error "Given IP address: ${2} must be available on host machine"
fi


CELL="${DEFAULT_CELLS_LOCATION}/${JAIL_HOSTNAME}"
SENTRY="${DEFAULT_SENTRY_LOCATION}/${JAIL_HOSTNAME}"
JAIL_ID_FILE="${SENTRY}/jail.id"
JAIL_SOURCE="${DEFAULT_JAIL_SHARED_LOCATION}/${SYSTEM_NAME}-${DEFAULT_VERSION}-${SYSTEM_ARCH}"

${GREP_BIN} "${JAIL_HOSTNAME}" ${JAIL_CONFIGURATION_FILE} > /dev/null 2>&1
if [ "$?" = "0" ]; then
    note "Jail configuration already in ${JAIL_CONFIGURATION_FILE}"
else
    note "Generating jail configuration"
    ${PRINTF_BIN} "
${JAIL_NAME} {
    name = \"${JAIL_NAME}\";
    host.hostname = \"${JAIL_HOSTNAME}\";
    ip4.addr = \"${JAIL_ADDRESS}\";
    interface = ${JAIL_INTERFACE};
    path = \"${CELL}\";
    exec.start = \"/bin/sh /etc/rc\";
    exec.stop = \"/bin/sh /etc/rc.shutdown\";
    enforce_statfs = 1;
    allow.mount = 1;
    allow.mount.nullfs = 1;
    allow.mount.zfs = 1;
    allow.mount.tmpfs = 1;
    allow.raw_sockets = 1;
    mount.devfs;
    persist;
}
" >> ${JAIL_CONFIGURATION_FILE}
fi


note "Copying jail directories"
zfs create -o mountpoint=${CELL} zroot${CELL}
zfs create -o mountpoint=${SENTRY} zroot${SENTRY}
${CP_BIN} -R ${JAIL_SOURCE}/ ${CELL}

note "Making required jail directories"
${MKDIR_BIN} -p ${CELL}/tmp ${CELL}/dev ${CELL}/Software ${CELL}/SystemUsers

note "Installing default etc for jail"
${TAR_BIN} xf ${DEFAULT_ETC_ARCHIVE} --directory ${CELL}
${SED_BIN} -i '' -e "s:__JAIL_NAME:${JAIL_HOSTNAME}:" ${CELL}/etc/rc.conf

note "Removing unnecessary directories"
${RM_BIN} -rf ${CELL}/boot

note "Installing Sofin"
if [ -d "/tmp/sofin" ]; then
    cd /tmp/sofin
    ${GIT_BIN} reset --hard
    ${GIT_BIN} pull https://github.com/VerKnowSys/sofin.git
else
    cd /tmp
    ${GIT_BIN} clone https://github.com/VerKnowSys/sofin.git
    cd sofin
fi
PREFIX=${CELL} bin/install
${CP_BIN} -R /Software/Git ${CELL}/Software
${CP_BIN} -R /Software/Zsh ${CELL}/Software
${CP_BIN} -R /Software/Vim ${CELL}/Software
${CP_BIN} /etc/zshenv ${CELL}/etc

note "Launching jail: ${JAIL_HOSTNAME}"
${JAIL_BIN} -qcmr -J ${JAIL_ID_FILE} 2> /dev/null

