#!/bin/sh
#
# $FreeBSD: releng/10.1/etc/rc.d/autounmountd 270892 2014-08-31 21:18:23Z trasz $
#

# PROVIDE: autounmountd
# REQUIRE: nfsclient
# KEYWORD: nojail

. /etc/rc.subr

name="autounmountd"
rcvar="autofs_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
