#!/bin/sh

. /etc/sofin.conf.sh


CELL_ATTRIBUTE_FILE="jail.ip.address"

DEFAULT_CELLS_LOCATION="/Jails/Prison/Cells"
DEFAULT_SENTRY_LOCATION="/Jails/Prison/Sentry"
DEFAULT_JAIL_SHARED_LOCATION="/Jails/Shared"

cd ${DEFAULT_CELLS_LOCATION}
for cell in $(${LS_BIN}); do
    cellname="$(${PRINTF_BIN} "${cell}" | ${AWK_BIN} '{print substr($1,0,29);}')" # first 29 chars visible in jls output
    ${PRINTF_BIN} "${cellname}"
    IP="${cyan}no-IP-assigned${reset}"
    if [ -f "${DEFAULT_SENTRY_LOCATION}/${cellname}/${CELL_ATTRIBUTE_FILE}" ]; then
        IP="${cyan}$(${CAT_BIN} "${DEFAULT_SENTRY_LOCATION}/${cellname}/${CELL_ATTRIBUTE_FILE}")${reset}"
    fi
    ${JLS_BIN} | ${GREP_BIN} "\ ${cellname}\ " > /dev/null 2>&1
    if [ "$?" = "0" ]; then
        ${PRINTF_BIN} " ${IP} ${gray}(${green}*on*${gray})${reset}"
    else
        ${PRINTF_BIN} " ${IP} ${gray}(${red}*off*${gray})${reset}"
    fi
    ${PRINTF_BIN} "\n"
done
