#!/bin/sh

. /etc/sofin.conf.sh


SERVED_REPO="/var/ServeD-OS"
DEFAULT_CELLS_LOCATION="/Jails/Prison/Cells"
DEFAULT_SENTRY_LOCATION="/Jails/Prison/Sentry"
DEFAULT_JAIL_SHARED_LOCATION="/Jails/Shared"
DEFAULT_VERSION="10.1"
DEFAULT_INTERFACE="$(${ROUTE_BIN} show -net 0 | ${TAIL_BIN} -n 4 | ${HEAD_BIN} -n 1 | ${AWK_BIN} '{print $2;}')"
DEFAULT_ETC_ARCHIVE="${SERVED_REPO}/jail-utils/etc-jail.tar.xz"
DEFAULT_WORKER_UID="501"
DEFAULT_QUOTA_LIMIT="5G"
DEFAULT_SENTRY_LIMIT="128M"

usage () {
    note "Usage: $(${BASENAME_BIN} $0) jail-name.com IP-address fbsd-version net-interface"
    note "fbsd-version -> by default 10.1"
    note "net-interface -> by default first interface with default route (${DEFAULT_INTERFACE})"
}


if [ ! -f "${DEFAULT_ETC_ARCHIVE}" ]; then
    error "etc archive: ${DEFAULT_ETC_ARCHIVE} wasn't found. Cannot continue"
fi

JAIL_HOSTNAME="${1}" # hostname?
if [ "${1}" = "" ]; then
    usage
    error "No jail hostname given"
fi
JAIL_NAME="$(${PRINTF_BIN} "${JAIL_HOSTNAME}\n" | ${SED_BIN} 's/\./-/g')"

JAIL_ADDRESS="${2}"
if [ "${2}" = "" ]; then
    note "No ip given"
    usage
    exit 1
fi

JAIL_VERSION="${3}"
if [ "${3}" = "" ]; then
    JAIL_VERSION="${DEFAULT_VERSION}"
fi

JAIL_INTERFACE="${4}"
if [ "${4}" = "" ]; then
    JAIL_INTERFACE="${DEFAULT_INTERFACE}"
fi


CELL="${DEFAULT_CELLS_LOCATION}/${JAIL_HOSTNAME}"
SENTRY="${DEFAULT_SENTRY_LOCATION}/${JAIL_HOSTNAME}"
JAIL_ID_FILE="${SENTRY}/jail.id"
JAIL_CONF_FILE="${SENTRY}/jail.conf"
JAIL_TRACE_LOG="${SENTRY}/jail.truss.log"
JAIL_SOURCE="${DEFAULT_JAIL_SHARED_LOCATION}/${SYSTEM_NAME}-${JAIL_VERSION}-${SYSTEM_ARCH}"
JAIL_VERSION_FILE="${SENTRY}/jail.os.version"
JAIL_ADDRESS_FILE="${SENTRY}/jail.ip.address"
JAIL_ATTRIBUTES_DIR="${SENTRY}/jail-attributes"
JAIL_DOMAINS_DIR="${SENTRY}/jail-domains"
JAIL_WEBSERVER_CONF_DIR="${SENTRY}/jail-webconf"

note "Creating ZFS dataset"
zfs create -o mountpoint=${CELL} zroot${CELL}
zfs set quota=${DEFAULT_QUOTA_LIMIT} zroot${CELL}
zfs create -o mountpoint=${SENTRY} zroot${SENTRY}
zfs set quota=${DEFAULT_SENTRY_LIMIT} zroot${SENTRY}

if [ -f "${JAIL_CONF_FILE}" ]; then
    warn "Jail configuration already in ${JAIL_CONF_FILE}"
else
    note "Generating jail configuration"
    ${PRINTF_BIN} "
${JAIL_NAME} {
    name = \"${JAIL_NAME}\";
    host.hostname = \"${JAIL_HOSTNAME}\";
    ip4.addr = \"${JAIL_ADDRESS}\";
    interface = ${JAIL_INTERFACE};
    path = \"${CELL}\";
    exec.start = \"/bin/sh /etc/rc\";
    exec.stop = \"/bin/sh /etc/rc.shutdown\";
    enforce_statfs = 2;
    allow.mount = 0;
    allow.mount.nullfs = 0;
    allow.mount.zfs = 0;
    allow.mount.tmpfs = 0;
    allow.raw_sockets = 1;
    mount.devfs;
    persist;
}
" >> ${JAIL_CONF_FILE}
fi

note "Mounting jail directories"
for dir in bin lib libexec sbin usr; do
    ${MKDIR_BIN} -p "${CELL}/${dir}"
    ${MOUNT_NULLFS} -o ro "${JAIL_SOURCE}/${dir}" "${CELL}/${dir}"
done

note "Copying volatile part of jail"
${PRINTF_BIN} "${JAIL_VERSION}\n" > ${JAIL_VERSION_FILE}
${PRINTF_BIN} "${JAIL_ADDRESS}\n" > ${JAIL_ADDRESS_FILE}
${CP_BIN} -R ${JAIL_SOURCE}/etc ${CELL}
${CP_BIN} -R ${JAIL_SOURCE}/var ${CELL}

note "Making required jail directories and user dir"
${MKDIR_BIN} -p "${JAIL_WEBSERVER_CONF_DIR}"
${MKDIR_BIN} -p "${JAIL_ATTRIBUTES_DIR}"
${MKDIR_BIN} -p "${JAIL_DOMAINS_DIR}"
${MKDIR_BIN} -p ${CELL}/tmp ${CELL}/dev ${CELL}/Software ${CELL}/SystemUsers ${CELL}/User/.ssh
${CHOWN_BIN} -R ${DEFAULT_WORKER_UID} ${CELL}/User ${CELL}/Software ${CELL}/tmp

note "Installing default etc for jail"
${TAR_BIN} xf ${DEFAULT_ETC_ARCHIVE} --directory ${CELL}
${SED_BIN} -i '' -e "s:__JAIL_NAME:${JAIL_HOSTNAME}:" ${CELL}/etc/rc.conf

note "Removing unnecessary directories"
${RM_BIN} -rf ${CELL}/boot ${CELL}/mnt ${CELL}/media ${CELL}/rescue ${CELL}/root ${CELL}/proc

${CP_BIN} -R /Software/Git ${CELL}/Software
${CP_BIN} -R /Software/Zsh ${CELL}/Software
${CP_BIN} -R /Software/Vim ${CELL}/Software
${CP_BIN} /etc/zshenv ${CELL}/etc

note "Launching jail: ${JAIL_HOSTNAME}"
jail-start "${JAIL_HOSTNAME}"

