#!/bin/sh

. /etc/sofin.conf.sh


DEFAULT_CELLS_LOCATION="/Jails/Prison/Cells"
DEFAULT_SENTRY_LOCATION="/Jails/Prison/Sentry"
UMOUNT_BIN="/sbin/umount"


usage () {
    note "Usage: $(${BASENAME_BIN} $0) jail.tld.com"
}


JAIL_HOSTNAME="${1}" # hostname?
if [ "${1}" = "" ]; then
    usage
    error "No jail to stop"
fi
JAIL_NAME="$(${PRINTF_BIN} "${JAIL_HOSTNAME}\n" | ${SED_BIN} 's/\./-/g')"
CELL="${DEFAULT_CELLS_LOCATION}/${JAIL_HOSTNAME}"
SENTRY="${DEFAULT_SENTRY_LOCATION}/${JAIL_HOSTNAME}"
JAIL_CONF_FILE="${SENTRY}/jail.conf"
JAIL_ID_FILE="${SENTRY}/jail.id"
JAIL_TRACE_LOG="${SENTRY}/jail.truss.log"
JAIL_ADDRESS_FILE="${SENTRY}/jail.ip.address"
DEFAULT_INTERFACE="$(${ROUTE_BIN} show -net 0 | ${TAIL_BIN} -n 4 | ${HEAD_BIN} -n 1 | ${AWK_BIN} '{print $2;}')"

note "Terminating jail: ${JAIL_HOSTNAME}"
${TRUSS_BIN} -o ${JAIL_TRACE_LOG} ${JAIL_BIN} -r "${JAIL_NAME}"

note "Unmounting jail directories"
for dir in dev bin lib libexec sbin usr; do
    ${UMOUNT_BIN} "${CELL}/${dir}" 2>/dev/null
done

IP="$(${CAT_BIN} ${JAIL_ADDRESS_FILE})"
note "Turning off jail IP: ${IP}"
ifconfig ${DEFAULT_INTERFACE} ${IP} -alias

