#!/bin/sh

. /etc/sofin.conf.sh


usage () {
    note "Usage: $(${BASENAME_BIN} $0) jail.tld.com"
}

JAIL_HOSTNAME="${1}" # hostname?
if [ "${1}" = "" ]; then
    usage
    error "No jail to enter"
fi
DEFAULT_JAIL_SHARED_LOCATION="/Jails/Shared"
DEFAULT_SENTRY_LOCATION="/Jails/Prison/Sentry"
SENTRY="${DEFAULT_SENTRY_LOCATION}/${JAIL_HOSTNAME}"
JAIL_EXEC_LOG="${SENTRY}/jail.truss.exec.log"
JAIL_NAME="$(${PRINTF_BIN} "${JAIL_HOSTNAME}\n" | ${SED_BIN} 's/\./-/g')"

note "Logging into jail: ${JAIL_HOSTNAME}"
${TRUSS_BIN} -o ${JAIL_EXEC_LOG} ${JEXEC_BIN} ${JAIL_NAME} login -f worker
