#!/bin/sh

. /etc/sofin.conf.sh

usage () {
    note "Usage: $(${BASENAME_BIN} $0) jail.tld.com"
}

CELL_ATTRIBUTE_FILE="jail.ip.address"

DEFAULT_CELLS_LOCATION="/Jails/Prison/Cells"
DEFAULT_SENTRY_LOCATION="/Jails/Prison/Sentry"
DEFAULT_JAIL_SHARED_LOCATION="/Jails/Shared"

JAIL_HOSTNAME="${1}" # hostname?
if [ "${1}" = "" ]; then
    usage
    error "No jail hostname given"
fi
CELL="${DEFAULT_CELLS_LOCATION}/${JAIL_HOSTNAME}"
SENTRY="${DEFAULT_SENTRY_LOCATION}/${JAIL_HOSTNAME}"
JAIL_DOMAINS_DIR="${SENTRY}/jail-domains"
JAIL_CONF_FILE="${SENTRY}/jail.conf"
JAIL_ATTRIBUTES_DIR="${SENTRY}/jail-attributes"
JAIL_NAME="$(${PRINTF_BIN} "${JAIL_HOSTNAME}\n" | ${SED_BIN} 's/\./-/g')"

STATUS="${gray}(${red}*off*${gray})${reset}"
${JLS_BIN} | ${GREP_BIN} "\ ${JAIL_HOSTNAME}\ " > /dev/null 2>&1
if [ "$?" = "0" ]; then
    STATUS="${gray}(${green}*on*${gray})${reset}"
fi
IP="${cyan}no-address${reset}"
if [ -f "${DEFAULT_SENTRY_LOCATION}/${JAIL_HOSTNAME}/${CELL_IP_ADDRESS_FILE}" ]; then
    IP="${cyan}$(${CAT_BIN} "${DEFAULT_SENTRY_LOCATION}/${JAIL_HOSTNAME}/${CELL_IP_ADDRESS_FILE}")${reset}"
fi

HOSTNAMES=""
for hostn in $(${FIND_BIN} ${JAIL_DOMAINS_DIR} -type f 2>/dev/null); do
    HOSTNAMES="*.$(${BASENAME_BIN} ${hostn}) ${HOSTNAMES}"
done

${PRINTF_BIN} "Name: ${green}${JAIL_NAME}${reset}\n"
${PRINTF_BIN} "Hostnames: ${green}${HOSTNAMES}${reset}\n"
${PRINTF_BIN} "IPv4: ${IP}\n"
${PRINTF_BIN} "Status: ${STATUS}\n\n"

if [ -d "${JAIL_ATTRIBUTES_DIR}" ]; then
    ${PRINTF_BIN} "Overriden attributes:\n"
    for i in $(${FIND_BIN} ${JAIL_ATTRIBUTES_DIR} -type f); do
        ${PRINTF_BIN} "${cyan}$(${BASENAME_BIN} ${i}): $(${CAT_BIN} ${i})${reset}\n"
    done
    ${PRINTF_BIN} "\n"
fi
${PRINTF_BIN} "Live attributes:\n${cyan}$(${RCTL_BIN} -h jail:${JAIL_NAME} | ${SED_BIN} 's/jail:n1://g' | ${SED_BIN} 's/:deny=/: /g')${reset}\n"
${PRINTF_BIN} "\nFull configuration:"
${PRINTF_BIN} "${cyan}$(${CAT_BIN} "${JAIL_CONF_FILE}")\n"
