#!/bin/sh

. /etc/sofin.conf.sh

DEFAULT_CELLS_LOCATION="/Jails/Prison/Cells"
DEFAULT_SENTRY_LOCATION="/Jails/Prison/Sentry"
DEFAULT_JAIL_SHARED_LOCATION="/Jails/Shared"

cd ${DEFAULT_CELLS_LOCATION}
for cell in $(${LS_BIN}); do
    cellname="$(${PRINTF_BIN} "${cell}" | ${AWK_BIN} '{print substr($1,0,29);}')" # first 29 chars visible in jls output
    ${PRINTF_BIN} "${cellname} "
    ${JLS_BIN} | ${GREP_BIN} "\ ${cellname}\ " > /dev/null 2>&1
    if [ "$?" = "0" ]; then
        ${PRINTF_BIN} "(${green}*on*${reset})"
    else
        ${PRINTF_BIN} "(${red}*off*${reset})"
    fi
    ${PRINTF_BIN} "\n"
done
